### ISSUE TITLE
A typo in 'help_rus/GEDKeeper2.html' file

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#11]
There's a small typo in the following text in 'locales/help_rus/GEDKeeper2.html' file:

> . . .
> ## Форумы
> Форум Cибирской генеалогии
> . . .

The letter 'С' in the 'Сибирской' word is English letter 'C' [siː] not a Russian letter 'С' [es] :microscope:

**Comment by Serg-Norseman** [comment]
Oh, I didn't even think to tell you that an article with resources in the Internet which is very specific for Russia, translate probably not worth it :( I'm sorry, I didn't think :(

**Comment by ruslangaripov** [comment]
It's OK. Anyway, I've done, I've translated this page. If you won't like it -- we can throw it out at any time. So do not worry about that! :ok_hand:

**Comment by Serg-Norseman** [comment]
Once done, the work can not be destroyed! Leave
