### ISSUE TITLE
Notes with tildes don't display correctly

### ISSUE THREAD

**Issue by fire-eggs** [Serg-Norseman/GEDKeeper#117]
I have a GEDCOM where an INDI record has the following note:
```
1 NOTE http://freepages.genealogy.rootsweb.ancestry.com/~thorodin/familly-p/p
2 CONC 4662.htm#i73888
```

If it displays at all, it is displayed in the Note view as `http://freepages.genealogy.rootsweb.ancestry.com/`. I.e. the full text is truncated and the "Links:" back to the INDI is missing.

**Comment by Serg-Norseman** [comment]
My oversight. In viewer of text notes and summaries of records, the tilde is used to markup the text. I'll try to think of something to fix.

**Comment by fire-eggs** [comment]
I'm learning a lot by poking at GEDKeeper, thank you so much for this project!
