### ISSUE TITLE
Overlapping boxes in descendants tree

### ISSUE THREAD

**Issue by fire-eggs** [Serg-Norseman/GEDKeeper#118]
Using the attached GEDCOM file, the 'Descendants tree" view shows children boxes overlapping
(selected individual is 'surname given name'):

![image](https://cloud.githubusercontent.com/assets/9809727/23319012/d75536da-faa2-11e6-99ff-b2aaeee5cecf.png)

[allged.zip](https://github.com/Serg-Norseman/GEDKeeper/files/800359/allged.zip)

**Comment by Serg-Norseman** [comment]
This issue failed to reproduce on a similarly constructed tree. The problem is somewhere in the file structure. I will be looking.

**Comment by Serg-Norseman** [comment]
It turns out that the error occurs only if in the first family, the second child has no gender. Strange thing...

**Comment by Serg-Norseman** [comment]
Similar issue #189

**Comment by Serg-Norseman** [comment]
Old bug not found.
