### ISSUE TITLE
`UDN` uses irreversible JDNs.

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#12]
Currently `UDN` framework uses JDNs of integer type.

And because `CalendarConverter.{calendar}_to_jd` methods produce floating-point values, we lose precision and get irreversible JDNs.

For example, '2016/05/31' date gives '2457539' integer JDN. And integer '2457539' JDN gives... '2016/05/30'!

[Algorithms from Wikipedia](https://en.wikipedia.org/wiki/Julian_day) give reversible **integer** values. But it provides ready formulae only for Julian and Gregorian calendars. We have to re-implement analogous formulae for other calendars by ourself (well, actually I'm ready).

Or we have to use JDNs of floating-point type. This is difficult since UDN framework stores JDN and some bit flags together, in one 32bit value. I believe we can find some free bits in 64bit double, but this won't be as easy and straightforward as with integer value. We will have to "crack" IEEE Standard 754 for floating-point format.

 :neckbeard:

**Comment by Serg-Norseman** [comment]
Maybe close the question? How many thought - the new bits are not needed; the reversibility of now generally there, although not very correct.

**Comment by ruslangaripov** [comment]
To be perfectly frank, we did **not** fix the problem :smiling_imp: 

The most perfect way to fix it, is to implement the [algorithms from Wikipedia](https://en.wikipedia.org/wiki/Julian_day) operating with integer values. Thus, we eliminate usage of floating-point values. Of course, this will require some time, but I'm ready to lose it, because the game **is worth** the candle -- we'll get reversible JDN values.

If we select "cracking IEEE Standard 754 standard", we pick yet another an unsteady way, where we change underlying data storage. Just as we already did. But because we have already did that, we may go further and try to use double precision floating-point values instead of current 32-bit value.

So, here is my decision: the current UDN implementation does not give irreversible JDNs. While it must. If GEDKeeper can live with that -- this make our programmer lives easy :smiling_imp: But before we might close this ticket **completely**, we must try to fix it. I'll try to implement the both solutions (integer algorithms and 64-bit floating-point values) at the bitbucket repository. Just give me a time, please!

**Comment by Serg-Norseman** [comment]
Time - no problem! :)
I'll just suggest this: I think you don't have to deal with the change of algorithms and format of IEEE 754 doubles. If you want to continue this theme: then, IMHO, you need to develop integer JD and formulas from Wikipedia. I'll too try to find such formulas for missing calendars.

**Comment by ruslangaripov** [comment]
> you don't have to deal with the change of algorithms and format of IEEE 754 doubles

Why not? We have already broken one format (double word). Why wouldn't we break an another one? :smiling_imp: If we could, of course.

**Comment by Serg-Norseman** [comment]
Check this out, now unexpectedly found: http://aa.quae.nl/en/reken/juliaansedag.html

**Comment by ruslangaripov** [comment]
What I've implemented using http://aa.quae.nl/en/reken/juliaansedag.html:

1. JDNs made from dates in Gregorian and Julian calendars are completely reversible.
2. JDNs made from dates in Islamic calendar are completely reversible (and it looks like, they were).
3. JDNs made from dates in Jewish calendar are reversible... occasionally (while the current 'Fourmilab Calendar Converter' always gives reversible values for Jewish calendar).

For example,
*Jewish date -> JDN -> Jewish date*
4682/3/18 -> 2057986 -> 4682/3/18 (no error, okay)
4684/7/1 -> 2058441 -> 4684/7/1 (fine)
3761/10/18 -> 1721426 -> 3761/10/-12 (oops :confused:)
3761/12/1 -> 1721468 -> 3761/11/1 (not good again)
3762/11/1 -> 1721791 -> 3762/10/27 (what's that?)
3762/12/2 -> 1721822 -> 3762/11/29 (:finnadie:)
3762/13/29 -> 1721879 -> 3762/13/26 (:bomb:)
3763/1/1 -> 1722234 -> 3763/1/1 (starting from this date everything becomes correct)

**Comment by Serg-Norseman** [comment]
Fixed by 49999c960cedd86bccc5ea8740d8a6e829d3f6f4
