### ISSUE TITLE
Use Google calendars for holiday greetings

### ISSUE THREAD

**Issue by g10101k** [Serg-Norseman/GEDKeeper#121]
Subject

**Comment by ruslangaripov** [comment]
Can you give more details about your "question"? :smiley:

**Comment by g10101k** [comment]
@ruslangaripov  , I suggest using external service (Google Calendar) to get a list of nashional holidays

**Comment by ruslangaripov** [comment]
I see. Is Google Calendar available if user isn't signed in?

Yours truly,
Ruslan Garipov <ruslanngaripov at gmail dot com>.
----------------------------------------------
MinGW-w64 developer, with write after approval
GEDKeeper collaborator

**Comment by Serg-Norseman** [comment]
My personal opinion is that the dependence on online services is evil. But we can think about...

**Comment by Serg-Norseman** [comment]
I decided that another dependence on online service with the need to maintain boundary quota for requests is unacceptable
