### ISSUE TITLE
Cache photo

### ISSUE THREAD

**Issue by g10101k** [Serg-Norseman/GEDKeeper#123]
If two persons refer to one picture, cache is created only one

**Comment by ruslangaripov** [comment]
Therefore, if you remove such portrait from the first person, the second loses the cached image? That is the issue? I think one cached image for several people with the same portrait (is it possible at all? 😜) is ok.

**Comment by g10101k** [comment]
Case: 
Photo contain two image person's. If this photo used for two portrait then happen bug. Tree will be use last  or first cache.

**Comment by ruslangaripov** [comment]
I got it! In such case user selects areas on the doubled image and then 
he/she gets the same image for two different people in tree chart.

See also: #116.

Yours truly,
Ruslan Garipov <ruslanngaripov at gmail dot com>.
----------------------------------------------
MinGW-w64 developer, with write after approval
GEDKeeper collaborator
