### ISSUE TITLE
Add Unified numbers of dates framework

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#16]
https://bitbucket.org/Serg-Norseman/calendarconverter (@Serg-Norseman; @ruslangaripov)

**Comment by ruslangaripov** [comment]
- [ ] Add approximate dates into UDN framework.

**Comment by Serg-Norseman** [comment]
Went through and rechecked the tests in the project on bitbucket, no errors noticed. In the tests with the DB too, no errors detected. Will also view different databases and close.

**Comment by Serg-Norseman** [comment]
Check all the databases showed that all is working correctly. If in the future there will be problems - we will correct them in working order, as bugs. Will review more code everywhere - may need cleanup, then I close this issue.

**Comment by ruslangaripov** [comment]
I agree. If we do not have any additional tasks, related to the issue (some new kind of dates, for example, or new underlying data type -- see ticket #12 ), we may close this ticket.

**Comment by Serg-Norseman** [comment]
Not found any significant points for improvement or cleanup of  code that is associated with UDN. Close.
