### ISSUE TITLE
I can't run 'GKImageViewerPlugin' plug-in built with make [bug]

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#18]
After I have built 'GKImageViewerPlugin' plug-in binaries, I couldn't use it.

GEDKeeper shows no GUI for the plug-in and the next text appears in the program's log:

> [11.05.2016 9:27:32] -> GKImageViewerPlugin.Execute(): Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "GKImageViewerPlugin.IVPResource.resources" was correctly embedded or linked into assembly "GKImageViewerPlugin" at compile time, or that all the satellite assemblies required are loadable and fully signed.

After I had debugged the issue I've found out its source:
**File**: projects\GKImageViewerPlugin\ImageViewerWin.cs
**Code**:

```csharp
public ImageViewerWin(IPlugin plugin)
{
    . . .
(1)    this.tbFileLoad.Image = IVPResource.iLoad;
    . . .
```

Line (1) causes this exception:
> Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "GKImageViewerPlugin.IVPResource.resources" was correctly embedded or linked into assembly "GKImageViewerPlugin" at compile time, or that all the satellite assemblies required are loadable and fully signed.

The problem is similar to one we had with GEDKeeper itself :smiling_imp:

**Comment by ruslangaripov** [comment]
Please assign 'bug' label to this ticket! Thx! :bug:
:smiling_imp:

**Comment by Serg-Norseman** [comment]
Tonight I will examine the issue with the resources in these subprojects.
