### ISSUE TITLE
Marriage Surname Not Available

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#190]
When editing an individual, the marriage surname textbox is not available (it is greyed out).
![married_surname](https://user-images.githubusercontent.com/8588144/55375971-1e95cb00-54c3-11e9-8322-71333a4c97eb.jpg)

**Comment by Serg-Norseman** [comment]
Since this function is not covered by the GEDCOM standard, it is enabled by a separate option 
(Service \ Options \ Interface \ All lists \ Additional names \ Extended woman's surnames).

**Comment by Serg-Norseman** [comment]
How did you so carelessly write this question in the project PicoeEto.
I think that their community in shock from this question  :D

**Comment by Dreamer451** [comment]
I’ve no idea how I got to their repository. Call me *embarrassed*

Kevin Sandal

**Comment by burtek** [comment]
@Serg-Norseman quick question regarding the above - does the "Extended woman's surnames" work for male entries, too? In Poland both husband and wife can change their surname or keep the "original" one (it happens rarely, but is a case in my family) and as far as I can see, the "Extended woman's surnames" enabled the married surname field for women entries, but it doesn't on men entries?

**Comment by Serg-Norseman** [comment]
Until now, this was only required for women. Of course, we can also include it for men (in future versions). But in the general case, according to the standard, additional “full names” are intended for this - the “Names” tab of the person editing dialog.

Are you sure you need to use the non-standard "marriage surname"? Maybe an additional name with the subtype "married" would be more appropriate?

If not, please add an issue with this request. I will make an additional factor for unlocking extended surnames in marriage with reference to language/culture - in your case, Polish.

**Comment by burtek** [comment]
@Serg-Norseman I'm actually working on and old database from 2008 and only learning gedcom etc now. Thanks for pointing me to the Names tab, will use it!

Having said that, is there an easy way to convert `_MARN` and `_MARNM` fields to 'married' type name?
