### ISSUE TITLE
Terminal UI

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#195]
I know it doesn't make sense, but this one:
https://github.com/migueldeicaza/gui.cs - so cute! 

Breath of time ... motives of DOS and consoles ...

Can we make GEDKeeper in such an implementation?

**Comment by ruslangaripov** [comment]
If we would find a person interested -- why not.

What I've started thinking about recently is CLI-based programs :-)

**Comment by ruslangaripov** [comment]
Why did you close it?  🤔😀

Yours truly,
Ruslan Garipov <ruslanngaripov at gmail dot com>.
----------------------------------------------
MinGW-w64 developer, with write after approval
GEDKeeper collaborator

**Comment by Serg-Norseman** [comment]
Well, in the near future I definitely will not do this. This can only go as entertainment, there is no real sense.

And besides me and you, who else can do this?

**Comment by Serg-Norseman** [comment]
And besides, I keep all such questions in a special mailstone so that they are closed (do not loom before my eyes) and so that we can easily find any in the future.

**Comment by Serg-Norseman** [comment]
I prefer a clean task list, when the all difficult or unpromising nonsense does not distract attention. We can always reopen.

**Comment by ruslangaripov** [comment]
I see 😀👍

Yours truly,
Ruslan Garipov <ruslanngaripov at gmail dot com>.
----------------------------------------------
MinGW-w64 developer, with write after approval
GEDKeeper collaborator
