### ISSUE TITLE
Update and fixes English manual

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#198]
In the help files the kbd HTML tag shows text as very small. If an entry was made in styles.css to override it, then greater control can be made. Changing the font color slightly for example.
![firefox](https://user-images.githubusercontent.com/8588144/56843820-18dd9c00-685b-11e9-8600-296e0adbf360.jpg)

**Comment by Serg-Norseman** [comment]
Understood, I do not mind. A good idea!

**Comment by Dreamer451** [comment]
In the file gkhFeatures.html file there are several statements about how GEDKeeper has non-standard extensions, and refer to them as an advantage. Later on there is a reference to how third-party software uses non-standard extensions and it is bad they do so.

I wonder if the term non-standard is inaccurate here. Are the GEDKeeper extensions non-standard because they do not follow the GEDCOM standard for extensions? Or are GEDKeeper's extensions non-standard because of another reason?

**Comment by Serg-Norseman** [comment]
Good question ... I need to think :)

**Comment by Serg-Norseman** [comment]
> GEDKeeper itself adds non-standard extensions to GEDCOM specification to store and process social groups, researches, tasks and correspondence. Most genealogical software has such extensions but unfortunately they are all non-standard. There were repeated attempts undertaken in the past to develop new GEDCOM specification included these extensions, but all attempts failed.

Here, both in this and in the Russian text, my accents are unfortunate. I agree to yours attempt to write another version of this fragment. The essence of the matter is as follows:
- The program has a number of non-standard extensions for data structures;
- Similar or other extensions are in most other programs; they are all non-standard by definition;
- In itself, the presence of certain non-standard extensions is not bad, it is quite normal; the very possibility of creating extensions in the standard is, but not formalized in detail;
- The only bad thing is that the extensions are similar in purpose, all the developers do it differently, not trying to agree and create a new standard.

**Comment by Serg-Norseman** [comment]
Suggestions for the best titles for this and the initial issues are accepted

**Comment by Serg-Norseman** [comment]
About the "absmiddle" - I myself worked with this issue. According to the standard, this is really outdated functionality. I just do not like that with the "middle" icons are displayed in the line below the center line. And with "absmiddle" everything is in the center of the line. Tested in Firefox. As in other browsers, I do not know. Let's leave it as it is, and it is permissible to edit in other files. But it is as ugly ...

**Comment by Dreamer451** [comment]
Before I submit a commit, please take a look at this FAQ file. Since other manual pages are using bullets (unordered lists), I changed this one to also use bullets. If acceptable I will make the commit.
[Frequently Asked Questions.pdf](https://github.com/Serg-Norseman/GEDKeeper/files/3139721/Frequently.Asked.Questions.pdf)

**Comment by Serg-Norseman** [comment]
yes, can replace markers to bullets here. It will probably be more convenient. Only one thing - come on with different commits. Edit the text separately, change the format separately. So text verification will be faster.

**Comment by Dreamer451** [comment]
Regarding `gkhPluginStd.html`, there is a phrase used repeatedly: 

> a standard service plugin

Is this a reference to a plugin that is, by default, installed? Or is this an actual service (daemon)--and I just cannot see it? I believe the former, but I do not wish to guess.

**Comment by Dreamer451** [comment]
Discussion point: should text like "-homedir:path" and "%APPDATA%\GEDKeeper2" have their own style? I believe they should. We could use the "kbd" style, for example.

**Comment by Serg-Norseman** [comment]
Yes it is possible

**Comment by Serg-Norseman** [comment]
#206

**Comment by Serg-Norseman** [comment]
In one of the previous versions, this possibility became limited only with the "Allow direct references to media files" option enabled (Options\Multimedia).

**Comment by Dreamer451** [comment]
Are you wanting 5 commits at most to be submitted at a time, or is that 5 files per commit at most? I believe it is the later, but I want to be sure.

**Comment by Serg-Norseman** [comment]
With regard to the manual files that you are correcting - one file is better per commit - just for the convenience of discussing and commenting on the improvements. That in comments to commit not to specify every time about what file there is a speech (let it usually and obviously).

Commits at a time (and before pull request), it is better not more than 5-6 - this is an acceptable and convenient amount that can be discussed and changed at a reasonable time - so that the changes do not accumulate and we not be confused in the degree of completion. Then send the pull request and after it merge go to the new files / commits.

I have given comments to the past four files. One or two had to be completed. Will you return to them?

**Comment by Dreamer451** [comment]
I only see requested changes to commit c506287--which is done.

**Comment by Dreamer451** [comment]
In gkhRec_Repo.html there are references to "Archive records". These are a type of record within repositories, correct? As in a "state archive" is a repository of information controlled by a state...yes?

**Comment by Serg-Norseman** [comment]
Yes, in the gkhRec_Repo file, we need to change part of the words "archive" to "repository". This is a translation error, because we have a Russian analogue of the word "repository" rarely used in relation to a similar concept. If we use a literal translation, then we will have the "State Archives". Therefore, in the Russian version of this article, our analogue of the word "repository" was not used. I would suggest the following - let me correct the English version so that the correct words are in meaning. And then you fix everything else?

**Comment by Dreamer451** [comment]
Sounds good.

**Comment by Serg-Norseman** [comment]
Then I will change the text right now in your fork (online) and write when you can continue your edits.

**Comment by Serg-Norseman** [comment]
Do a `pull` or` fetch` operation in your local repository folder to pick up my change. And you can continue

**Comment by Dreamer451** [comment]
In `gkhTools_TreeCheck.html` it states that after the check if a person does not have a sex defined that the sex editor dialog would appear. In practice the repair on that record assigns "male" to the person automatically. Is the manual page out of sync with the program, or is the program operating unexpectedly?

**Comment by Serg-Norseman** [comment]
There is both a feature and potentially unexpected behavior. The fact is that in the process of loading files, the program automatically collects refbook of names. Together with the name is recorded and sex. Therefore, the function of checking the base, where it is necessary to correct the unknown sex of a person, can look in the refbook and if there is such a name - automatically assign a sex.

Unfortunately, in many countries of the world there are many names of "dual use". Therefore, potentially this module may give a false result.

**Comment by Dreamer451** [comment]
Is it safe to commit the next set?

**Comment by Serg-Norseman** [comment]
Yes. No problem :)

**Comment by Dreamer451** [comment]
FYI: I have gone through all the pages. This first iteration makes them better, but there is plenty that could still be done.

**Comment by Serg-Norseman** [comment]
I do not see the problem. Let's try to speed it up a bit. I fast check the articles if there are no big format changes. So let's bring the next set of files to 10 pieces. For now, we only complete the proofreading of the text. If you have ideas for further improving the manual, then let's discuss them all in this issue. Something can be send immediately in the work, something to postpone.

In the issue "Update manuals: common questions," I began to make a plan to further improve the manuals. There I will add more items that we will do together. I especially need to take the time and look through past discussion issues to discover the items that need to be synchronized across both manuals for common development.

**Comment by Dreamer451** [comment]
Is it time to go through the English manual pages and put in the language declaration?

**Comment by Serg-Norseman** [comment]
Yes of course

**Comment by Serg-Norseman** [comment]
Completed.
