### ISSUE TITLE
HTML standards compliance in manual pages

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#204]
Per the HTML standards, the `<!DOCTYPE>` declaration must be the very first thing in your HTML pages. This explicitly tells the client that it is an HTML encoded document.

To ensure proper decoding by the client, the `<HTML>` declaration should be `<HTML lang="en">` for English and `<HTML lang="ru">` for Russian.

The align attribute `absmiddle` is obsolete. Should use either `middle` or CSS.

The `img` elements should have an `alt` attribute for situations where the client does not render images. For example, Firefox and Chrome have extensions that may disable the automatic display of images.

**Comment by ruslangaripov** [comment]
Can you give links and quotes from the standards you've mentioned?  Except the last note about the `img` tag (yes, `alt` attribute is necessary *for me*, because I view **all** sites without images and scripts by default :-D).

**Comment by Serg-Norseman** [comment]
For absmiddle, we need an analogue that would look neatly in the text line, in the middle vertically. If this question had been worked out without mistakes, as had been made at the beginning of our interaction, then there would be no questions.

Edits should not destroy the appearance of the document that already exists. Only improvement is allowed.

**Comment by Serg-Norseman** [comment]
And the experiments should not be carried out on files in the project. You want to promote some way - make a demo, an example of a file with the desired style and send it on the mail.

I do not want to see going back and forth in my project when some changes are first made without agreement. Then it turns out to be a mistake and everything changes back.

**Comment by Dreamer451** [comment]
HTML standards can be found at https://www.w3.org/standards/. They provide a validator at https://validator.w3.org/. `DOCTYPE` specifics can be found at https://www.w3.org/QA/2002/04/valid-dtd-list.html.

I believe that the appearance of the documents can be maintained by using CSS and therefore be compliant with standards.

**Comment by Serg-Norseman** [comment]
By the way, I know about DOCTYPE and HTML for a long time. All this is known, not a mystery. I just thought it was useless trifle. It is necessary to develop the functions of the project, develop content. And this HTML-compatibilities can be done later. These standards are created without stopping, will not escape anywhere. 

Good. When we make the main content correction manual. I'll think about upgrading the structure. Only a separate stage. Now - just remember this, no action.

**Comment by ruslangaripov** [comment]
> the <!DOCTYPE> declaration must be the very first thing in your HTML pages.

```sh
$ pwd
.../gedkeeper/locales/help_enu

$ grep -L -e '<!DOCTYPE html>' *.html

```

Therefore, does the English manual currently has such files (without doctype specified)?  Or you talk about the Russian manual?

**Comment by Dreamer451** [comment]
Neither Russian or English have the `DOCTYPE` declaration.

**Comment by Serg-Norseman** [comment]
mmm!

**Comment by Dreamer451** [comment]
I have not taken action to implement compliance as you can see by my commits to-date. I just wanted it to be a trackable issue for addressing in the future. If I am misunderstanding the purpose of the "Issues", then please correct me. I will always take constructive criticism well.

**Comment by ruslangaripov** [comment]
> Neither Russian or English have the `DOCTYPE` declaration.

Are you sure?

```sh
$ head -n 3 gkhAbout.html
<!DOCTYPE html>
<html>
<head>

$ git log --oneline | head -n1
c564a790 Merge branch 'master' of https://github.com/Serg-Norseman/GEDKeeper
```

**Comment by Serg-Norseman** [comment]
Kevin, did you look at those files exactly? In each file of the English manual there is a doctype!

**Comment by Dreamer451** [comment]
Between looking and writing up the issue, I had a brain fart. It is not that the `DOCTYPE` is missing, but rather that it does not have the attribute of which version of the HTML standard is used (4.01, XHTML 1.0, etc.). Without the attribute it will be considered by modern browsers to be 5.x compliant. Example:
`<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "DTD/xhtml1-strict.dtd">`

**Comment by ruslangaripov** [comment]
Just for future reference.  About the html tag[1]:

> Authors are encouraged to specify a lang attribute on the root html element, giving the document’s language. This aids speech synthesis tools to determine what pronunciations to use, translation tools to determine what rules to use, and so forth.

[1] https://www.w3.org/TR/html52/semantics.html#the-html-element

**Comment by Dreamer451** [comment]
FYI: a decent list of the `DOCTYPE`s is at http://alistapart.com/article/doctype/.

**Comment by Serg-Norseman** [comment]
Oh my god ... When will we discuss with the same zeal how to make the program more cool ... :(

Well, someday we do these tags, to hell with them. I give a tooth - when the content is finished, we will think about improving compatibility with standards.

And all this is not that. This is all internal. It gives nothing to the project. Nothing!

**Comment by Dreamer451** [comment]
I disagree. It does provide value if we use the W3C validator to validate the HTML. To-date I have just ignored the incompatibilities I referenced. However, it is easy to miss incompatibilities that may impact a client's rendering.

All that said, I am not suggesting this is oh-my-god-let-us-change-it-now type of scenario. What I am suggesting is that after I have gone through all the pages and they have been committed, then this could be addressed. Reviewing the changes at that point will be simplistic.

Finally, I look forward to being done with the manual pages. They are providing valuable insight into how the program operates--which is making understanding the mechanics of the program easier. I miss actual coding and hope that I can contribute to the program itself in the near future.

**Comment by ruslangaripov** [comment]
> I look forward to being done with the manual pages

Unix man-pages? 😲

**Comment by ruslangaripov** [comment]
> incompatibilities that may impact a client's rendering

The current versions of the manuals (both the Russian and English ones) use some kind of fundamental HTML formatting.  Which just can't be rendered incorrectly with a stable browser.

**Comment by Serg-Norseman** [comment]
Yes, of course. No sane browser will not go to remove outdated functionality. He will immediately begin to lose market share and users, because the Internet is chock full of obsolete pages, 90% of which no one will ever rewrite. Except for corporate marketing rubbish.

**Comment by Serg-Norseman** [comment]
Come on, it would still have to be done. Just now everything is not a good time. Flies separately, cutlets separately. All in due time. Here is my final decision.

**Comment by Serg-Norseman** [comment]
With all these disputes and my work, I have done almost nothing that I planned for this week. This is sadness ...

**Comment by Dreamer451** [comment]
It is sadness. Perhaps you could give up sleep and any type of personal life?   ;)

**Comment by ruslangaripov** [comment]
Enough.  We slipped into a non-productive discussion.  This **SHALL** be avoided in the future.

This issue, just as its neighbor #205, must be closed now as a postponed one with \`\`**might**-be-reviewed-later'' mark.

**Comment by Dreamer451** [comment]
I agree.

Sorry if I offended you.

**Comment by Serg-Norseman** [comment]
This issue, should have been one whole with the next. I do not see the difference between them.

**Comment by Serg-Norseman** [comment]
> I miss actual coding and hope that I can contribute to the program itself in the near future.

We have a certain culture of the project, which has been developing for 10 years since 2009. In many aspects, this culture is specific to this project and adopted under my strong influence.

In addition, the program is being developed taking into account the mass of compromises that are not visible from the outside and have not been formalized in any way. There are also a number of conservative users who enjoy my strong support, and therefore many progressive methods known to me are not used in order not to destroy their work opportunities. I like to develop a program on the border of affordable very old systems (WinXP). Because I will never force people to switch to new technologies, who taught me professional genealogy, who have been doing this for decades and have accumulated funds of hundreds of thousands of names in their bases. They deserve a calm and stable work on their old computers, the right to do their work, not understanding the annually changing trends of modern software and operating systems.

I’m confused by your empty profile without any projects of your own since 2014. It is alarming and makes us guess about your abilities, preferences, style and level of development. I have already come across the fact that a person who suddenly came from the outside wanted to redo the whole project under peak frameworks and rebuild the whole stack of methods used under the most fashionable trends. Because of my work, I come across all of this, I know and use a lot - at work, in a team where our task is corporate industrial software. But I see no reason to use it all in my personal project as long as the real requirements do not force us to apply something new. And if new methods require the destruction of compatibility with previous systems - I throw out new methods.

I hope that all this will not become a stumbling block.

**Comment by Dreamer451** [comment]
Nothing in my bio because my latest work was custom Access work for my church. Before that was 24 years at Boeing developing stuff I cannot talk about. Thinking about it, I could at least put my scooling up. I will have to give it thought.Sent via cell phone, so please excuse brevity and spelling errors."Wherever you go, there you are."
-------- Original message --------From: Sergey Zhdanovskih <notifications@github.com> Date: 5/3/19  01:38  (GMT-08:00) To: Serg-Norseman/GEDKeeper <GEDKeeper@noreply.github.com> Cc: Kevin <kdsandal@gmail.com>, Assign <assign@noreply.github.com> Subject: Re: [Serg-Norseman/GEDKeeper] HTML Standards Compliance in Manual
  Pages (#204) 

I miss actual coding and hope that I can contribute to the program itself in the near future.



We have a certain culture of the project, which has been developing for 10 years since 2009. In many aspects, this culture is specific to this project and adopted under my strong influence.

In addition, the program is being developed taking into account the mass of compromises that are not visible from the outside and have not been formalized in any way. There are also a number of conservative users who enjoy my strong support, and therefore many progressive methods known to me are not used in order not to destroy their work opportunities. I like to develop a program on the border of affordable very old systems (WinXP). Because I will never force people to switch to new technologies, who taught me professional genealogy, who have been doing this for decades and have accumulated funds of hundreds of thousands of names in their bases. They deserve a calm and stable work on their old computers, the right to do their work, not understanding the annually changing trends of modern software and operating systems.

I’m confused by your empty profile without any projects of your own since 2014. It is alarming and makes us guess about your abilities, preferences, style and level of development. I have already come across the fact that a person who suddenly came from the outside wanted to redo the whole project under peak frameworks and rebuild the whole stack of methods used under the most fashionable trends. Because of my work, I come across all of this, I know and use a lot - at work, in a team where our task is corporate industrial software. But I see no reason to use it all in my personal project as long as the real requirements do not force us to apply something new. And if new methods require the destruction of compatibility with previous systems - I throw out new methods.

I hope that all this will not become a stumbling block.



—You are receiving this because you were assigned.Reply to this email directly, view it on GitHub, or mute the thread.

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Serg-Norseman/GEDKeeper","title":"Serg-Norseman/GEDKeeper","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/Serg-Norseman/GEDKeeper"}},"updates":{"snippets":[{"icon":"PERSON","message":"@Serg-Norseman in #204: \u003e I miss actual coding and hope that I can contribute to the program itself in the near future.\r\n\r\nWe have a certain culture of the project, which has been developing for 10 years since 2009. In many aspects, this culture is specific to this project and adopted under my strong influence.\r\n\r\nIn addition, the program is being developed taking into account the mass of compromises that are not visible from the outside and have not been formalized in any way. There are also a number of conservative users who enjoy my strong support, and therefore many progressive methods known to me are not used in order not to destroy their work opportunities. I like to develop a program on the border of affordable very old systems (WinXP). Because I will never force people to switch to new technologies, who taught me professional genealogy, who have been doing this for decades and have accumulated funds of hundreds of thousands of names in their bases. They deserve a calm and stable work on their old computers, the right to do their work, not understanding the annually changing trends of modern software and operating systems.\r\n\r\nI’m confused by your empty profile without any projects of your own since 2014. It is alarming and makes us guess about your abilities, preferences, style and level of development. I have already come across the fact that a person who suddenly came from the outside wanted to redo the whole project under peak frameworks and rebuild the whole stack of methods used under the most fashionable trends. Because of my work, I come across all of this, I know and use a lot - at work, in a team where our task is corporate industrial software. But I see no reason to use it all in my personal project as long as the real requirements do not force us to apply something new. And if new methods require the destruction of compatibility with previous systems - I throw out new methods.\r\n\r\nI hope that all this will not become a stumbling block."}],"action":{"name":"View Issue","url":"https://github.com/Serg-Norseman/GEDKeeper/issues/204#issuecomment-489009619"}}}

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/Serg-Norseman/GEDKeeper/issues/204#issuecomment-489009619",

"url": "https://github.com/Serg-Norseman/GEDKeeper/issues/204#issuecomment-489009619",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Serg-Norseman** [comment]
I removed from your answer everything that duplicated my previous message and the standard comments of the sending system. To avoid a large duplicate text. Excuse me.

**Comment by Serg-Norseman** [comment]
Your biography, resume and places of work did not interest me. None of us has a big reflection of our professional sphere on opensource and GitHub. Is that I have published here five projects that I did for work. I was interested in the level of skills in developing projects on .NET / C#. Also, the development of the project is influenced by my development experience in Java, and the experience of professional development in C ++ from Ruslan.

In this case, my main recommendation for you will be this: when you move on to development later, start implementing your ideas with writing some kind of your own plugins for the program in separate repositories. You will master the Core of the program, learn the subtleties of use, we will work out the interaction. I strongly do not recommend immediately trying to make any improvements in the Core or the main part of the project. Deep immersion in the use of the Core can also be obtained if you try to expand the coverage of the Core with unit tests. It is hard and difficult, but the effect will theoretically be stronger. Any attempts to make changes to the main project must obey the guidelines CONTRIBUTING and CODINGSTYLE. In addition, there are many requirements that have not yet been formalized. Prior to this, the development was carried out together with friends, with whom I could speak in my native language directly without correspondence, in a real conversation. Therefore, our interaction will proceed iteratively with the gradual elaboration and formalization of the rules of joint development.

**Comment by Serg-Norseman** [comment]
I see no point now. Therefore, no. When all the files are completed, then we will run through all the English and Russian files in one step at a time. By that time, there will probably be some other tasks for mass fixing. And now only 12 out of 70 are processed and accepted. Where to hurry?

**Comment by Serg-Norseman** [comment]
Completed.
