### ISSUE TITLE
HTML document formatting makes modifications difficult

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#205]
The formatting of the HTML manual pages makes modifications difficult. Most everything is left aligned--making it difficult to differentiate one section from another. I suggest using HTML-Tidy or an equivalent to "beautify" the files.

**Comment by ruslangaripov** [comment]
> I suggest using HTML-Tidy or an equivalent to "beautify" the files.

What that'll give us in terms of "making modifications more easily"?

**Comment by Serg-Norseman** [comment]
This is a bad decision when it comes to controlling such decisions through version control systems. A lot of levels, the text does not fit into the width of the screen, nothing can be controlled. Many edits will result in a change in line breaks.

This is discussed, but so far I do not like it. We'll see.

**Comment by Serg-Norseman** [comment]
The less levels, the easier it is to modify the text. I wanted to destroy all the indents in the Russian manual.

**Comment by Serg-Norseman** [comment]
In my opinion, creating a manual is a neat, unhurried process. Very thoughtful. Where to rush and engage in decoration?

**Comment by Dreamer451** [comment]
More than mere decoration, beautifying the code allows the editor to easily see different sections and easily identify unbalanced tags. As for effort, some tools, such as Visual Studio 2019, perform this process with a single mouse click.

**Comment by ruslangaripov** [comment]
I'm sorry, I'm believing "beautifying the code" is for human only.  If an editor can't find (for example) unbalanced tags in **correct** but written-in-one-line html file, well, I'd prefer don't use such editor.

**Comment by Serg-Norseman** [comment]
We will think about it. With time.

**Comment by Serg-Norseman** [comment]
Why do you in each issue make capital letters for each word in the title?

And I saw the same in the titles of the manual articles. Something seems to me that this is not correct. I have never seen anything like this anywhere.

**Comment by ruslangaripov** [comment]
It happens sometimes :-)  We don't use that style, but the English language does[1]:

> Using capital letters
>
> In the titles of books, films, organizations, etc.
>
> Use a capital letter in the titles of books and other publications, films, organizations, special days, etc. In such cases, you need a capital letter for all the main words but not for the connecting words such as *a*, *an*, *the*, *or*, *and*, etc.

I don't know does this rule can be applied here.  Just as an example[2]: FreeBSD Bugzilla does use this in its own title, but not in reports' titles.

[1] https://en.oxforddictionaries.com/spelling/using-capital-letters
[2] https://bugs.freebsd.org/bugzilla/buglist.cgi?component=amd64&product=Base%20System&resolution=---

**Comment by Serg-Norseman** [comment]
Did not know. Well, let it be, although it looks so strange ... They know better there.

But in the titles of issues, I will remove it later. Nowhere in the GitHub did I see such a thing, it interferes - as if the interlocutor is shouting his subject. It's like a solid capsloсk. Also perceived.
