### ISSUE TITLE
Calendar Plugin States Wrong Day of the Week

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#211]
If, for example, you click on May 17, 2019 on the calendar the display on the bottom shows that it is Saturday--when it is really Friday. This holds true for all dates--they are 1 day ahead for the day name.
![calendar](https://user-images.githubusercontent.com/8588144/57931374-293ad280-786d-11e9-8a9e-ce205fdd57f3.jpg)

**Comment by Serg-Norseman** [comment]
Fixed.

**Comment by Serg-Norseman** [comment]
Fixed.
