### ISSUE TITLE
"Compare databases" tool fails to find a duplicate

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#212]
![compare_database](https://user-images.githubusercontent.com/8588144/57958189-cf113000-78b3-11e9-870d-9cbc5efcd136.jpg)

The "Compare databases" tool fails to find this duplicate record when comparing the two separate databases.

**Comment by Serg-Norseman** [comment]
I will check and look for an error. Should work - this tool is often used... (((
