### ISSUE TITLE
GED to HTML (a plugin for generating static websites)

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#220]
User case: https://groups.google.com/forum/#!topic/gedkeeper-en/3Q4AU7tAi10

On March 30, I started the development of a future plug-in based on the GEDmill project.

GEDmill information: 
- author: Alexander Curtis;
- was shareware, but stopped by the author December 2008;
- published under the GPL license in November 2014;
- mature project;
- a rich set of opportunities;
- a good type of generated pages;

The process of converting a GEDmill project into a plugin for GEDKeeper was started as an experiment to increase the number of interesting tasks. Issues have not yet been.

I thank Kevin D. Sandal for great help in resolving the issues of correct use of the project GEDmill.

**Comment by Dreamer451** [comment]
It looks as if you are in the process of localization, so what assistance, if any, would you like? Or would you prefer I tackle a different item?

**Comment by Serg-Norseman** [comment]
This month I’m very overloaded, so I’m almost not involved in this project, because there are no minor problems that could be solved in my 20-30 minutes in the evening.

In the evenings, I program a little bit on another project for the soul, but only because there, in half an hour, I can do something significant without a thorough immersion.

Localization may require, according to my estimates, about a week of work with a thorough engagement in time.

You can do any direction in this plugin that you find interesting for yourself. After replacing the core and rebuilding the mass of mechanisms - I left a lot of tails and problems that need to be fixed. If you find them, create an issue with the prefix "GEDmill: <issue topic>". You can also make corrections if you are sure of the result. Even localization can be done by analogy with other plugins, although you probably are not interested in it.

But for good result, before localization, we need to complete the final refactoring and cleaning the plugin from bugs.

I recommend that you send a pull request with your recent changes before starting new ones :)
