### ISSUE TITLE
2.16.0 RC1 doesn't allow Reports or Plugins

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#223]
The Reports and Plugins menu options are disabled.

**Comment by Serg-Norseman** [comment]
Not reproduced. I unpack the archive in any folder. Run the executable file. All reports and plugins in place.

Write where and how you unpack the archive. Are there `plugins` subfolder in the unpacked folder, are there any files in it.

**Comment by Dreamer451** [comment]
I unpacked it to a temp folder (C:\apps\GEDKeeper216) and there are files in the plugins subfolder. If I can figure out how to debug it in VS2019 I'll step through the code to pinpoint the issue.

**Comment by Serg-Norseman** [comment]
It does not work out yet. I will look for...
Of course, you can also try to debug and look for an error.

**Comment by Dreamer451** [comment]
Oh bugger. Running this version through Visual Studio does not duplicate the issue. I will look into this issue further.

**Comment by Dreamer451** [comment]
I was able to reproduce the issue 6 times. The next 34 times were various stages of debugging and testing, and I could no longer reproduce the problem. I am closing this issue.

**Comment by Dreamer451** [comment]
Sorry if I overstepped. I should have said "I recommend closing this issue" and left the actual closing to you. My apologies.

**Comment by Serg-Norseman** [comment]
Actually, finally, try to take the error log from the appdata folder and send it to me in the mail. Maybe there is something there? To know for sure that all attempts to detect a problem have been exhausted.

**Comment by Dreamer451** [comment]
There were only two entries in the log file: `[2019-06-21 04:24:12] -> CLR Version: v4.0.30319` and `[2019-06-21 04:24:12] -> GK Version: 2.16.0.0`
I added a log file write in `BaseWinSDI.cs` at line 559, compiled, then ran it and it showed the value of `miPlugins.DropDownItems.Count` as zero. But only the first time I ran it.

**Comment by Serg-Norseman** [comment]
No, the place where you tried to write to the log is too late, far from the place where the plugins were loaded.

No, if the log is empty, then do not catch it. Errors are written to the log when loading plugins. If there are no plugins and the log is empty, then the problem is somewhere in the paths, and not in the plugins themselves. Probably a crash somewhere along the path the program is looking for plugins.

**Comment by Serg-Norseman** [comment]
You need to try to add:
`Logger.LogWrite("Plugins load path: " + path);`
to file `PluginsMan.cs` to line `76`

**Comment by Dreamer451** [comment]
I ran that section in the debugger with a breakpoint and the path was good. Nevertheless, I put in the code you suggested and, as expected, the plugins path is valid. I am unable to replicate the issue, but I had seen this behavior six consecutive times. Why on the seventh time and beyond it worked fine is a mystery.

**Comment by Serg-Norseman** [comment]
Yes. I have no new ideas yet :)
