### ISSUE TITLE
Double-clicking a .GED file doesn't open GEDKeeper with the file open

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#225]

**Comment by Dreamer451** [comment]
For some reason a post was made prematurely. The title was supposed to be "Double-clicking a .GED file doesn't open GEDKeeper with the file open". Description: I associated GEDKeeper with .GED files for easy opening but double-clicking the .GED file doesn't open GEDKeeper.

**Comment by Serg-Norseman** [comment]
I can not repeat the problem.

**Comment by Dreamer451** [comment]
I have tried with 2.15 and 2.16 RC 1 and the issue persists. It is 100% of the time. I used the Windows control panel 'app default' and it does not make a difference. The log file just shows the CLR version (4.0.30319) and the GK version. I will continue to investigate.

**Comment by Dreamer451** [comment]
Old GEDCOM software had left a footprint in the registry at HKCR\.ged and HKCR\GEDCOM.File that I had to manually remove. I then uninstalled GEDKeeper 2.15 then installed it and all works like it should now.
