### ISSUE TITLE
Exception during debugging in VS with high contrast OS settings enabled (or other themes)

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#227]
Build it and run using VS 2017 and when run with debug, initial form is displayed partially with exception:
`Visual Styles-related operation resulted in an error because no visual style is currently active`
When run it without debugging, it runs without problems.
_(Text cited from Milan Kosina)_

**Comment by Serg-Norseman** [comment]
Preliminary attempts to reproduce the problem showed that it is repeated with the OS contrasting theme set.

**Comment by m-kosina** [comment]
Tested and it works correctly now.

**Comment by Serg-Norseman** [comment]
No better and more correct solution was found.
