### ISSUE TITLE
Saved media with type "Saving to the archive" shows wrong "Store type"

### ISSUE THREAD

**Issue by m-kosina** [Serg-Norseman/GEDKeeper#228]
![2019-07-21_11-31-46](https://user-images.githubusercontent.com/52108003/61589557-e7e7db80-abab-11e9-89e7-0c6d3ac0bf1e.png)

Look at discrepancy between saved and displayed store type at the screenshot.

Problem is in 
`projects\GKCore\GKCore\Controllers\MediaEditDlgController.cs`
in 
`private void RefreshStoreTypes(bool allowRef, bool allowArc, MediaStoreType selectType)`
following line does not work:
`            fView.StoreType.SelectedTag = selectType;`
and first option is shown all the time.

This is probably due to the fact, that combobox is disabled. For "saving to the store" it works, as first options "Link to the file" is not added due to
`            if (allowRef) {`

**Comment by Serg-Norseman** [comment]
Good job! You have found a real bug in the implementation and have researched it well. If you want to fix it yourself and make your first pull request - I support and wish good luck!

**Comment by m-kosina** [comment]
In the Tuesday I'm leaving (vacation with wife, daughter and grandson), so I would prefer not to start fixing/broking the code now :) But after return I'll try to start helping :)

BTW the more I'm playing with the program - the more I like it! Really!

**Comment by Serg-Norseman** [comment]
In time of implementation - no restrictions or race, as your capabilities allow. And I am glad that you like the program so much :)
