### ISSUE TITLE
Locations missing Links part when event with this location is defaulted

### ISSUE THREAD

**Issue by m-kosina** [Serg-Norseman/GEDKeeper#229]
When event is created and event is leaved to default as in:

![image](https://user-images.githubusercontent.com/52108003/62409740-4c5b5f80-b5dc-11e9-896d-e0f16d6bb0c4.png)

![image](https://user-images.githubusercontent.com/52108003/62409747-55e4c780-b5dc-11e9-902f-5ae0240db03d.png)

it generates error in Locations tab, as when I select this location, no links are displayed (not only this one, but all):

![image](https://user-images.githubusercontent.com/52108003/62409767-84fb3900-b5dc-11e9-9c22-495c7bab8d95.png)

and in error log is written:
**[3.8.2019 8:25:08] -> GKUtils.ShowLocationInfo(): Object reference not set to an instance of an object.**

The source of the problem is in GKUtils GetEventName method, whic returns null in such situation, which throw exception in GetLocationLinks method on line 
**linksList.AddObject(GetRecordName(rec, true) + ", " + GetEventName(evt).ToLower(), rec);**

Fix for this is to add 
**?? LangMan.LS(GKData.PersonEvents[ev].Name)**

![image](https://user-images.githubusercontent.com/52108003/62409817-3bf7b480-b5dd-11e9-89e4-1d04382d3794.png)

(of course, it can also be handled in GetLocationLinks, but imo the null can cause problems also in other parts of the program, so propose this fix)

After this are links properly displayed:

![image](https://user-images.githubusercontent.com/52108003/62409807-179bd800-b5dd-11e9-9316-1cb7f3f6afde.png)

but also display of individual is changed:

![image](https://user-images.githubusercontent.com/52108003/62409812-297d7b00-b5dd-11e9-8454-5e0972543648.png)

and I'm not sure, if this is good in your opinion or not (for me it is ok). This fix can also changed visual behavior in other places (which I don't know), so it depends on you if you want to include it or not...

BTW I'm back from vacations just for 3 days, so there will be no source code posts to GitHub :)

**Comment by Serg-Norseman** [comment]
Great investigation!

You can make the correction you found and send a commit and pull request!
