### ISSUE TITLE
Displayed date formats are inconsistent

### ISSUE THREAD

**Issue by Dreamer451** [Serg-Norseman/GEDKeeper#238]
In `Service\Options\Interface\Date format in lists` I chose "YYYY.MM.DD" and this format is used in the lists. However, the information panel displays dates in the "DD.MM.YYYY" format. When dates are partial, such as just a month, then the displayed dates can be confusing.

**Comment by Serg-Norseman** [comment]
Implemented and tested.

The format for displaying dates in lists and on the information panel corresponds to the program settings. The format for displaying dates in tree diagrams is static, not subject to customization. Date format in input fields - corresponds to system settings.
