### ISSUE TITLE
'GKTreeVizPlugin' crashes GEDKeeper to desktop

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#24]
When I had tried to use 'GKTreeVizPlugin' plug-in, it killed the host application.

Steps to reproduce:
1. Run GEDKeeper,
2. Run 'GKTreeVizPlugin' plug-in from "Plug-ins" menu.
3. Accept default settings and click "Apply" button.
4. Nothing happens, but an error log entry appears in the application log (see below).
5. Wait for 3-5 seconds.
6. Click **any** menu or button on the tollbar.
7. New log entry appears in the log (also see below) and GEDKeeper crushes.

Step # 4 causes the following messages in the log:

> [13.05.2016 11:47:14] -> GK.ExExceptionHandler(): The type initializer for 'CsGL.OSLib' threw an exception.
> [13.05.2016 11:47:14] -> GK.ExExceptionHandler():    at CsGL.OpenGL.OpenGL..ctor()
>    at CsGL.OpenGL.GLUT..ctor()
>    at CsGL.OpenGL.OpenGLContext..ctor()
>    at CsGL.OpenGL.ControlGLContext..ctor(Control c)
>    at GKTreeVizPlugin.TreeVizControl.CreateContext()
>    at CsGL.OpenGL.OpenGLControl.get_Context()
>    at GKTreeVizPlugin.TreeVizControl..ctor()
>    at GKTreeVizPlugin.TreeVizViewer.InitializeComponent()
>    at GKTreeVizPlugin.TreeVizViewer..ctor(IBaseWindow aBase, Int32 minGens)
>    at GKTreeVizPlugin.Plugin.Execute()
>    at GKUI.MainWin.Plugin_Click(Object sender, EventArgs e)
>    at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
>    at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
>    at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
>    at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
>    at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    at System.Windows.Forms.Control.WndProc(Message& m)
>    at System.Windows.Forms.ToolStrip.WndProc(Message& m)
>    at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
>    at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
>    at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Step # 7 causes the following messages in the log:

> [13.05.2016 11:48:19] -> GK.UnhandledExceptionsHandler(): Could not load file or assembly 'ArborGVT, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified.
> [13.05.2016 11:48:19] -> GK.ExExceptionHandler():    at GKTreeVizPlugin.TreeVizControl.Dispose(Boolean disposing)
>    at System.ComponentModel.Component.Finalize()

I got the error on my Windows 10 :hankey: :laughing:

**Comment by Serg-Norseman** [comment]
I looked at this issue, the preliminary assumption that the reason for the x86/x64. While I will not go into makefiles, but try on this problem to change the compile mode to "x86 preferred". There is no assurance yet. Or, we'll do it differently - I recompiled in another mode ArborGVT. And I look - if the same problem occurs.

**Comment by Serg-Norseman** [comment]
No, remove the assumption: another assembly is the same, but works.

**Comment by ruslangaripov** [comment]
The makefiles use `AnyCPU` by default. And I believe I got the issue on this configuration (running on Windows 10 **x64** host).

1. Should I try to reproduce on x86 and x86-64 configurations?
2. Should we change makefiles' default hardware platform to 'x86'?
3. May be this is OpenGL issue? :smiling_imp:

**Comment by ruslangaripov** [comment]
> the preliminary assumption that the reason for the x86/x64

It is :smiling_imp: 

I made some releases by make and here is the results:

- 'release' and 'debug' configurations for x86 **always work**,
- any configurations for "direct" x86-64 or AnyCPU (and running the binaries on Windows x86-64) **always fail**.

Because you have eliminated x86-64 platform from supporting platform list, this ticket should be closed as "by design". May be we should remove support for x86-64 platform from makefiles too :disappointed: 

Well, sorry for bothering you! :tired_face: I'm really sorry! :confused:

**Comment by ruslangaripov** [comment]
Oh, by the way! :smiling_imp: This plug-in ain't localized when I run it from GEDKeeper having English localization.
