### ISSUE TITLE
Optimize regex searching in "Selecting record" form, as it now can take too much time

### ISSUE THREAD

**Issue by m-kosina** [Serg-Norseman/GEDKeeper#241]
It seems to me, that searching in Notes is now (minimally for my data) just too slow. When I tried to search in notes, it takes now around 40 secs.
In Performance Profiler is visible, that CPU is high and almost all the time is ListManager calling GKUtils.MatchesMask (Regex.IsMatch)

**Comment by Serg-Norseman** [comment]
Please test the correctness of this fix on your files.

**Comment by Serg-Norseman** [comment]
So far this is the best solution that I managed to come up with. Just a limiting factor. To find the speed improvement of regex itself is not working out yet.

**Comment by m-kosina** [comment]
Following code works for me (afaik I show it to you long time ago) - I'm doing regex only when necessary, otherwise I use plain indexOf and it is really quick. For the test I use very simple condition (presence of *), it should be done more correctly, but nevertheless imo it is how it should be done - dont use regex when not necessary
Original version:
```
            bool res = (QuickFilter == "*" || IsMatchesMask(fRec.Lines.Text, QuickFilter));
my version:
```
            bool res = QuickFilter == "*";
            if (!res) {
                string simpleFilter = QuickFilter.Substring(1, QuickFilter.Length - 2);
                if (QuickFilter.StartsWith("*")
                    && QuickFilter.EndsWith("*")
                    && !simpleFilter.Contains("*")) {
                    res = fRec.Lines.Text.IndexOf(simpleFilter, System.StringComparison.OrdinalIgnoreCase) >= 0;
                } else {
                    res = IsMatchesMask(fRec.Lines.Text, QuickFilter);
                }
            }

```

**Comment by Serg-Norseman** [comment]
I remember your version, I keep it in my thoughts. There is only a problem: the search string can contain the characters `?` and `|`. I use both. If you try to introduce them into your version, everything will turn out to be very complicated. I have only one option left: yesterday I found an old Microsoft code on pattern matching on state machine without regex. I can try to implement it in our project today. But `|` (or) is not supported there.

**Comment by m-kosina** [comment]
Sorry, dont understand, why is adding
```
&& !simpleFilter.Contains("*"))
&& !simpleFilter.Contains("?"))
&& !simpleFilter.Contains("|"))
````
complex?

**Comment by Serg-Norseman** [comment]
Yes, this is an variant :) I'll think about it

**Comment by Serg-Norseman** [comment]
I am trying to find an integrated overall approach. Try another new attempt, please :)

**Comment by m-kosina** [comment]
Much much better, not as fast as my simple approach, but it is normally usable :) Here I was typing kosina jan - 10 secs
![2020-06-04_16-11-17](https://user-images.githubusercontent.com/52108003/83767585-1ebcc800-a67e-11ea-9fbc-7a898c1e5f58.png)

**Comment by Serg-Norseman** [comment]
Try the new version, please :)

**Comment by m-kosina** [comment]
I'm not sending any screenshot, as there is nothing visible :D . It is really really quick and immediate :). It is not necessary to use my version any more. Thanks!

**Comment by Serg-Norseman** [comment]
I am very happy! I wish you successful and convenient researches! :)
