### ISSUE TITLE
HTTP 403 when selecting location

### ISSUE THREAD

**Issue by EddieDemon** [Serg-Norseman/GEDKeeper#248]
Hello,

When creating a new location, the location picker only shows a HTTP 403 Not Allowed error. "We are sorry, but we don't have imagery at this zoom level for this region."

Kind regards,
Eddie

**Comment by Serg-Norseman** [comment]
There is such a problem. Associated with with OpenStreetMaps, or with map processing in GMap.NET. I’ve been facing it for a long time, but I don’t know how to fix it ...
