### ISSUE TITLE
Broken link on the "Options" page in Russian help content

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#25]
'gkhOptions.html' file in Russian help content has a broken link in "Persons representation in the tree" section:

> ...Эти категории задаются при помощи раздела "[Сноски](gkhPersonUserRefs.html#tree)" в редакторе персон.

The link targets to "**gkhPersonUserRefs.html**#tree". And 'gkhPersonUserRefs.html' file doesn't exist. I believe it should target 'gkhRec_UserRefs.html' file, doesn't it?

**Comment by Serg-Norseman** [comment]
Yes, that's right

**Comment by ruslangaripov** [comment]
I fixed this in English localization while was translating :wrench:

**Comment by Serg-Norseman** [comment]
Ok! :) I'll change in the Russian help :)
