### ISSUE TITLE
Second first name displayed in a readonly 'Patronymic' combobox 

### ISSUE THREAD

**Issue by WalterRawley** [Serg-Norseman/GEDKeeper#253]
I don't understand why when someone has more than 1 first name, second first name and potential other ones are considered parts of "Patronymic". The problem is the patronymic is displayed as a disabled combo-box.

Take for exemple "Bach Carl Philipp" (from your Bach family sample) Philipp cannot be modified because it's displayed in patronymic field.

**Comment by WalterRawley** [comment]
I realised that there's a Russian culture set in Bach_Family.ged, which activates the patronymic field. But there's still a problem the patronymic is extracted in GKUtils.GetNameParts() even with no patronymic cultures.

**Comment by m-kosina** [comment]
I agree - I have the same findings. Here are steps to reproduce:
Open attached Err.ged file -its contents is:
0 HEAD
1 SOUR GEDKeeper
2 VERS 41
1 DEST GEDKeeper
1 CHAR UTF-8
1 LANG English
1 GEDC
2 VERS 5.5.1
2 FORM LINEAGE-LINKED
1 FILE Err.ged
2 _REV 2
1 DATE 01 JUN 2020
2 TIME 18:12:32.3
0 @I1@ INDI
1 _UID F5C255B5E0C8894089A3AF84A42B84FEE2B9
1 CHAN
2 DATE 01 JUN 2020
3 TIME 18:12:05.7
1 SEX M
1 NAME MaleName1 MaleName2 /MaleSurname/
2 SURN MaleSurname
2 GIVN MaleName1 MaleName2
1 BIRT
0 TRLR
On attached screenshot Err.png you will see current behaviour, on attached screenshot Ok.png you will see proper behaviour.
The fix will be to add into GetNameParts() method
...
            if (culture.HasPatronymic() && parts.Length > 1) {
...
            if (culture.HasPatronymic() && !string.IsNullOrEmpty(name) && string.IsNullOrEmpty(patronymic) && parts.Length > 1) {
...
but I dont know how to correctly pass context to access culture

[Err.zip](https://github.com/Serg-Norseman/GEDKeeper/files/4712350/Err.zip)

**Comment by Serg-Norseman** [comment]
Who can - please test the correctness of this fix on your files.

**Comment by m-kosina** [comment]
Works for me, thanks!

**Comment by Serg-Norseman** [comment]
@WalterRawley 
If you can, please take part in the completion of the translation and proofreading of the French localization of GEDKeeper at https://crowdin.com/project/gedkeeper
