### ISSUE TITLE
Help content says that user can create PDF

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#26]
There's a question I have: is currently an user always able to create PDF file (by exporting something from GEDKeeper) **under Linux**?

For example, 'gkhPedigrees.html' file from help content says:

> Родословная роспись формируется в виде PDF-файла ... (Pedigree is exported as a PDF file ...)

But as far as I know GEDKeeper has some problems with PDF under Linux (kick me if I'm wrong! :feelsgood:)

So, if I'm right, should we change GEDKeeper's help content (by adding a note about availability on Windows only, for example)?

Should we add new information about ability to export instances to HTML or RTF files?

**Comment by Serg-Norseman** [comment]
Yes, that's right. First, you need to add information on the possibility of export of the pedigrees in the html and rtf files. About export to pdf until the review is not done, because I found a couple of options. In the coming days will try to build and try. If nothing happens - then make a comment in the help. This issue was left open

**Comment by ruslangaripov** [comment]
OK! Then what about the following proposals. 

# Pedigrees ('gkhPedigrees.html')

Source (Russian) text:

> Родословная роспись формируется в виде PDF-файла с гиперссылками между персонами. Открывается сразу в той программе просмотра PDF, которая есть в системе, где её можно распечатать.

I've changed this to:

> There are several file formats you can export pedigrees to: HTML, RTF and PDF. The exported file includes hyperlinks between persons in the tree. Once GEDKeeper has created a target file, it then opens the file in a program, that was registered in your system as default action for the target file type. You can use that program, for example, to print the pedigree.
*Unfortunately, PDF export currently is available on Windows platforms only. PDF export on Linux currently is under heavily development.

The last paragraph is optional and will be removed once *exporting-to-pdf-under-linux* gone.

# Frequently asked questions ('gkhFAQ.html')

Source (Russian) text:

> г) Формирование родословных росписей с двумя типами нумерации по д'Абовиллю и Коновалову. Формируются в pdf-формате, печать из любой программы, работающей с pdf - от Adobe Acrobat до SumatraPDF...

I've putted this into English localization as:

>d) Create pedigrees having two schemes of numbering: d'Aboville's and Konovalov's schemes. Such pedigrees are created as HTML, RTF or PDF files and you can use any third party viewer, installed in your system (for example, [SumatraPDF](https://github.com/sumatrapdfreader/sumatrapdf) or Adobe Reader), to print such files.
*Unfortunately, PDF export currently is available on Windows platforms only. PDF export on Linux currently is under heavily development.

Once again -- the last paragraph is optional.

**Comment by ruslangaripov** [comment]
> If nothing happens - then make a comment in the help. This issue was left open

We can add a reference to this issue or another one directly in help's HTML files (in *the last paragraph* I have mentioned in the previous comment):

> *Unfortunately, PDF export currently is available on Windows platforms only. PDF export on Linux currently is under heavily development. For more information, please, view the [discussion on topic](https://github.com/Serg-Norseman/GEDKeeper/issues/26).

**Comment by ruslangaripov** [comment]
So, are you agree with my proposals? :smiling_imp:

I believe we must create a dedicated ticket for "PDF export issue on Linux". And refer that ticket in the next related commits and in help contents. I didn't create such ticket yet because I ain't aware of the problem enough, sorry.

**Comment by Serg-Norseman** [comment]
Sorry I haven't answered any of your proposals. Yesterday from 19 to 3 o'clock in the morning fought with three ways of generating the PDF under Linux. Very angry. All not good... I took a break for all tests.

**Comment by ruslangaripov** [comment]
Hold on!

May be it's better to discard PDF support away *temporarily*. Since this issue causes such problems :feelsgood:

**Comment by Serg-Norseman** [comment]
I made a decision, now. I freeze the development of the export to PDF under Linux. Don't know how, but the decisions do not see. Write in the help. On ticket does not refer, do not need to help make links to the development process. There is no export to PDF in Linux and all.

**Comment by ruslangaripov** [comment]
OK, I got it!

I believe you'll find a solution, sooner or later! :+1:

**Comment by ruslangaripov** [comment]
Fixed in English help content by b8e2da8 (wasn't pushed yet).
