### ISSUE TITLE
Support for non standard date formats

### ISSUE THREAD

**Issue by hazzik** [Serg-Norseman/GEDKeeper#260]
Recently I had issues with using GEDCOMs exported from Ancestry.com. The problem is that Ancestry allows dates to be present in all possible formats:
- It allows string months `21 Mar 1900`.
- It allows localized dates `21 Mär 1900` or `21 März 1900` (German)
- It allows dates without spaces `21MAR1900`

Worst of all it allows to mix-and-match different date styles in the same document.

In all these cases the month gets missing. And when I click save button the file GedKeeper saves an incomplete date without month.

![image](https://user-images.githubusercontent.com/144791/83810862-5b051e00-a6a8-11ea-84d2-536911fc6bc9.png)

**Comment by Serg-Norseman** [comment]
This is of course interesting :) But the development of high-quality imports from such a source will require information on all possible options. In order not to pull out the problem by small pieces ...

**Comment by Serg-Norseman** [comment]
The amazing thing: I received an issue from you yesterday, and today I stumbled upon your comment on one article on habr (I carefully read the comments, so I immediately saw a familiar name). 
:)
