### ISSUE TITLE
Photos cache is not invalidated after change

### ISSUE THREAD

**Issue by m-kosina** [Serg-Norseman/GEDKeeper#263]
When individual photo is changed, the old one is still displayed in the tree - even when GedKeeper is ended and started again. Imo should be invalidated some photo cache after the change of the photo. 
![2020-07-29_14-22-41](https://user-images.githubusercontent.com/52108003/88799607-090fde80-d1a7-11ea-9835-b630d05375c8.png)

**Comment by Serg-Norseman** [comment]
I have not been able to reproduce the problem.

**Comment by Serg-Norseman** [comment]
I still cannot reproduce this problem. No assumptions.

**Comment by Serg-Norseman** [comment]
The problem is not reproducible in any tests.
