### ISSUE TITLE
Icon size improvement on bar

### ISSUE THREAD

**Issue by jnezbeda** [Serg-Norseman/GEDKeeper#265]
On Linux I have worth user feeling. Icons on bar have smaller boxes. See Icon for 'Crate a new tree file'.

Others icons have same problem- tabs-bar must be situated on y-axis more down.

See also width-problem with Icon for 'Open the tree file'. 
![lubuntu_gedkeeper](https://user-images.githubusercontent.com/67690823/89896179-4c257500-dbdd-11ea-9f74-fba27ceb2bb1.jpg)

**Comment by Serg-Norseman** [comment]
My guess is that Mono + WinForms does a poor job of window rendering and relative positioning of components. Fixing this will be tricky :(
