### ISSUE TITLE
Linux version fails to start on Ubuntu Mate 20.04

### ISSUE THREAD

**Issue by mkaut** [Serg-Norseman/GEDKeeper#268]
I tried the latest Linux version of GEDKeeper (`gedkeeper_2.16.2-1_all.deb`) on Ubuntu Mate 20.04, but it does not start. There is no error message when started from the menu, but when I call `mono GEDKeeper2.exe` from within `/usr/lib/gedkeeper/`, I get the following:

```
Unhandled Exception:
System.TypeLoadException: Could not load type of field 'GKUI.Providers.WFAppHost:fAppContext' (0) due to: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not load type of field 'GKUI.Providers.WFAppHost:fAppContext' (0) due to: Could not load file or assembly 'System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
```

**Comment by Serg-Norseman** [comment]
The "Could not load file or assembly System.Windows.Forms" error indicates a problem with the version or completeness of the .NET Mono installation. We need to find out which version of Mono you have installed.

**Comment by mkaut** [comment]
I just installed mono-runtime from the main repo, which gave me `mono-runtime 6.8.0.105+dfsg-2`, satisfying GEDKeeper's dependency requirement of `>=5.12`.
Running `mono --version` returns:
```
Mono JIT compiler version 6.8.0.105 (Debian 6.8.0.105+dfsg-2 Wed Feb 26 23:23:50 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          supported, not enabled.
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by Serg-Norseman** [comment]
I recommend that you try installing `mono-complete`. 
`mono-runtime` may not be enough.

**Comment by mkaut** [comment]
I can confirm that installing `mono-complete` helps. I did not investigate which of the many packages in `mono-complete` did the trick. 
It could help to update the dependency information in the .deb file.

**Comment by Serg-Norseman** [comment]
I am glad that the problem was solved. I will take steps to eliminate this in the future. Thank you!
