### ISSUE TITLE
Interpreting negative years  (Geni)

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#272]
Source: GK Development chat (Telegram)

Interpretation of dates of the form:

1 BIRT
2 DATE BET -25 AND 29

**Comment by hazzik** [comment]
I think this can be closed

**Comment by hazzik** [comment]
Looks good, thanks. It can be closed now.

**Comment by Serg-Norseman** [comment]
Ok 👍
