### ISSUE TITLE
Incorrect source parsing (Geni)

### ISSUE THREAD

**Issue by hazzik** [Serg-Norseman/GEDKeeper#273]
The sources produced by Geni are appearing empty in the program.

![image](https://user-images.githubusercontent.com/144791/111543462-fe707c80-876a-11eb-930f-4f3b2dfeb210.png)

```
1 SOUR
2 DATA
3 DATE 29 APR 2020
3 TEXT Date of Birth
3 TEXT
2 OBJE
3 FILE https://photos.geni.com/p13/ed/5c/7d/5f/53444842db38e0e0/0052_original.jpg
4 FORM jpg
3 TITL Всероссийская сельскохозяйственная и поземельная перепись 1917 года
```

- [Tags.zip](https://github.com/Serg-Norseman/GEDKeeper/files/6159937/Tags.zip)

**Comment by Serg-Norseman** [comment]
To close this issue, I cannot work out how to handle SourceCitationData when transforming SourceCitation to reference form (GEDCOMChecker.TransformSourceCitation()). These objects do not directly correspond to GDMSourceData. It will not work to transform one into another.

**Comment by Serg-Norseman** [comment]
Please check the complexity of the implemented solution to this issue

**Comment by hazzik** [comment]
Looks good thanks. Not ideal, but I think good enough.
