### ISSUE TITLE
Вопросы по использованию GEDKeeper

### ISSUE THREAD

**Issue by altwarg** [Serg-Norseman/GEDKeeper#276]
Сергей, благодарю вас за столь качественное ПО! Давно искал нечто подобное.

По мере использования ПО возникли некоторые вопросы, ответы на которые я не нашел в документации, настройках или в issue на GitHub / Tracker на SourceForge:
1. При добавлении персоны присутствуют checkbox'ы "Патриарх" и "Закладка". Какую функцию они предоставляют?
2. Заметил, что в списке персон столбец "Возраст" отображает округленную в большую сторону количество лет персоны (если жива). Возможно ли отображение также с учетом месяцев и дней (например, `23 года, 8 месяцев, 2 дня`)?
3. Правильно я понимаю, что в разработке использовался стек технологий с Windows Forms и часть на .NET Standard? И что Linux-версия, представленная .deb-пакетом в комплекте идет с средой Mono?

**Comment by Serg-Norseman** [comment]
1. Маркеры "Патриарх" и "Закладка" - это почти одно и тоже. Это закладки для удобства сортировки в таблице персон и для фильтрации персон. Патриархами я обычно помечаю последнее известное лицо любого пола по каждой ветви предков (чаще это всё таки мужчина). Закладка - условно просто как закладка в книге, пометка для быстрой сортировки на следующий сеанс работы. Более навороченного использования для них пока не предусмотрено.
2. Отображение возраста с учетом месяцев и дней потенциально можно разработать, но это потребует времени. Нужно будет решить ряд практических моментов в случаях неполных дат.
3. В разработке основной линии проекта (сейчас это направление GEDKeeper "2"), используется только .NET Framework 4.0 и WinForms. Основная причина выбора dotnet40, как максимальной версии .NET - поддержка ряда очень мной уважаемых пользователей, которые по разным причинам до сих пор работают на WinXP. Причина фиксированного использования WinForms - то, что он поддерживается в неизменном виде в Mono (стек WPF в Mono отсутствует). В случае перехода на .NET Core для Linux, теряется WinForms и нужно будет подобрать адекватный UI-фреймворк (несколько лет назад в выборе участвовали Eto, Avalonia, Xamarin, Xwt). Также одновременно разрабатывалась и сейчас слабо поддерживается будущая реализация GKv3 на базе фреймворка Eto. Там уже можно проект компилировать под .NET Core и для Linux бакэнд базируется на Gtk, а для Windows бакэнд основан на WPF. GKv2 и GKv3 - это не поколения, но параллельные ветви развития под разные UI и рантаймы. Базовая часть GKv3 на основе Eto давно разработана и работает, требуется только развитие дизайна, в основном виде он недалеко ушел от WinForms, выглядит похоже. Также предпринимались экспериментальные попытки реализации GK на базе Xamarin и UWP (ветви существуют до сих пор), но там дальше реализации прототипа дело не ушло по указанной в предыдущем Issue причине - нужен дизайнер для разработки качественной темы стилей в XAML.

Вопросы подобного плана лучше обсуждать следующими способами: 
форум https://groups.google.com/g/gedkeeper-ru,
чат общих вопросов https://t.me/gedkeeper_chat_ru,
чат разработки https://t.me/gedkeeper_dev_ru

**Comment by Serg-Norseman** [comment]
Добавлю, что Linux дистрибутив GEDKeeper для Debian/Ubuntu не включает в себя Mono, но содержит требование её установки. К сожалению, из-за проблем с неустановкой неизвестного мне пакета Mono, необходимого для работы WinForms, требование к Mono недавно пришлось расширить mono-runtime до mono-complete. Последний ставит слишком много лишнего, но необходимо целое исследование: какие именно пакеты кроме mono-runtime необходимы для работы WinForms.

Также относительно GKv3/Eto релиза: там также возможно использование стилей/тем. Несколько в урезанном виде по сравнению с XAML в WPF, но насколько я видел - авторы Eto улучшают поддержку XAML. Кроме того, там есть способ использовать полноценный набор стилей в сборке под конкретный рантайм. Т.к. Windows-бакэндом Eto является WPF - если бы была достойная тема, можно было бы построить качественный дизайн GKv3 хотя бы под Windows.

Также в Eto есть и поддержка мобильных платформ, но кажется пока это не доминирующее направление.

**Comment by Serg-Norseman** [comment]
При сравнении различных UI фреймворков в первую очередь учитывалось наличие всех необходимых визуальных компонентов с идентичным поведением. 

Xamarin и Avalonia не то что отброшены полностью. Но помехой стало например то, что в обоих отсутствовал полноценный ComboBox, который поддерживал бы не только выпадающий список пунктов, но и редактирование "inplace". Это важно в нескольких местах программы. Это фактор навскидку. Были и другие проблемы.

XWT зарождался исходя из традиций построения и именования компонентов и их функций, как привычно для разработчиков Gtk (предположительно). Т.е. для типичного разработчика .NET под Windows - слишком непривычная структура классов, их функций и свойств. Для создания графического приложения с нуля это несущественно. А когда стоит задача перенести приложение с большим количеством форм - это помеха и сильно раздражающий фактор.
