### ISSUE TITLE
The main window doesn't save its position

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#29]
I have the following monitor configuration on my desktop: two monitors standing near each other. The primary one is on the right side.

If I had moved the main window to the left (not primary) monitor and then I closed the window **there**, next time I run the application, the main window appears **on the primary screen** :bug: 

This is the source of the issue:

File: projects\GEDKeeper2\GKCore\GKUtils.cs

```csharp
public static ExtRect GetFormRect(Form form)
{
    if (form == null) return ExtRect.CreateEmpty();

    int x = form.Left;
    int y = form.Top;
    int w = form.Width;
    int h = form.Height;
    Screen scr = Screen.PrimaryScreen;
    int mw = scr.WorkingArea.Width;
    int mh = scr.WorkingArea.Height;
    if (x < 0) x = 0;
    if (y < 0) y = 0;
    if (w > mw) w = mw;
    if (h > mh) h = mh;
    return ExtRect.Create(x, y, x + w - 1, y + h - 1);
}
```

where problem lines are:

```csharp
public static ExtRect GetFormRect(Form form)
{
    . . .
    if (x < 0) x = 0;
    if (y < 0) y = 0;
    if (w > mw) w = mw;
    if (h > mh) h = mh;
    . . .
}
```

As you can see `x` can't be a negative number (that's true in my case). Moreover, had I two monitors, located one above another, I would get the same problem with `y`. Had I four monitors in staggered-order, I would get both the problems simultaneously.

A similar issue can arise with window size. For some *unknown* reason size of the window get restricted to the size of **primary screen**. But what if I have worked on another monitor?

The code that sets `x` and `y` to zero must be changed to code that check availability of some window coordinates **on the application startup** and not before shutting it down. And for my configuration: if I was working on the left monitor, in normal cases the main window must appear on that monitor. But if for some reason I have lost that monitor (disconnected it), the main window get automatically moved to the primary monitor.

Concerning size of the window. I don't know should we limit it. If we must, we must use entire desktop size. Not a monitor's one. After all, in my configuration I can stretch the window from the left monitor to the right one. It's a (very) rare case but I can. And a good application must save this information between its sessions.

I can't fix it right now. Because I don't have enough knowledge about USER objects in .NET. But I'm gonna study it! :smiling_imp:

**Comment by Serg-Norseman** [comment]
At home I have two monitors, so the problem is urgent. I have habit and just have not noticed difficulties with it. We will solve.

**Comment by ruslangaripov** [comment]
> At home I have two monitors

My home configuration includes one ancient 17" Viewsonic :feelsgood:

 :sunglasses: But there is many a good tune played on an old fiddle! :smiling_imp:
