### ISSUE TITLE
Interchanged translations in German locale

### ISSUE THREAD

**Issue by cbettinger** [Serg-Norseman/GEDKeeper#313]
I am using GedKeeper with German localization. I noticed the names and surnames of individuals being interchanged when I import the GEDCOM file into any other tool.

The reason is a simple error in locales/german.lng (which lead me to enter names and surnames into the wrong input fields):

```
085=Vorname
086=Name
```

It should be:

```
085=Name
086=Vorname
```

**Comment by Serg-Norseman** [comment]
Thank you for your message. I'll fix the error :)

**Comment by cbettinger** [comment]
Just in case somebody has the same problem, I made a simple Node.js script to swap surnames and given names within GEDCOM files:

https://github.com/cbettinger/gedcom-swap-surn-givn

Usage (backup file gets created, original file is overwritten):

```node swap.js myGedcomFile.ged```

**Comment by Serg-Norseman** [comment]
The project has already fixed this problem. I plan to release the new version around May 14-16.

**Comment by Serg-Norseman** [comment]
Your correction will certainly be useful for those who entered data in the wrong input fields. Thank you!

Probably, a high-quality proofreading of localization files is required, at least for the correctness of key terms. But I don't know how to accomplish this yet.

**Comment by Serg-Norseman** [comment]
If you can, please take part in the completion of the translation and proofreading of the German localization of GEDKeeper at https://crowdin.com/project/gedkeeper
