### ISSUE TITLE
Is there redundant text in help content ("Person" page)?

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#33]
This is what we have in 'gkhRec_Individual.html' file:

> * Такие-же кнопки [images], и под именем каждого из родителей отвечают за другое: кнопка [image] - добавляет новую семью, если никакая не была подключена ранее, и добавляет в неё конкретного родителя (отца или мать), кнопка [image] соответственно отсоединяет из присоединенной к человеку семьи выбранного родителя (отца/мать).
* Для добавления родителей, следует в секциях "Отец" или "Мать" нажать на кнопку "Выбрать или добавить отца(мать)" [image]. Соответственно, чтобы убрать данные - следует нажать на кнопку "Отсоединить отца(мать)" [image]. Также возможны быстрые переходы на записи родителей по кнопкам [image].

*Translation for English readers:*

> * The same buttons: [images], and located under the name of each parent perform other functions. [image] button adds new family if one was not added already, and then adds to this family the concrete parent (father or mother). [image] button removes from a parent (father or mother) from person's family.
* To add a parent, you use [image] button -- "Select or add father (mother)" in "Father" or "Mother" section, respectively. To remove a parent, you use button -- "Detach father (mother)". To quickly jump to a parent's person record you use [image] button.

I think both paragraphs should be combined because they are almost the same.

**Comment by Serg-Norseman** [comment]
I agree, my oversight. It is necessary to unite. If you can change also the Russian text.

**Comment by Serg-Norseman** [comment]
I see you have a GPG signature made? Good thing, I think, necessary for me to do. I can then still distros for Linux to sign as it should be....

**Comment by ruslangaripov** [comment]
>It is necessary to unite. If you can change also the Russian text.

Sure, I will!

**Comment by ruslangaripov** [comment]
>I see you have a GPG signature made?

Yep, I did. But currently l'm signing nothing except git objects 😈

**Comment by ruslangaripov** [comment]
New combined paragraph now looks like this:

> * Такие-же кнопки [images], и под именем каждого из родителей отвечают за другое: кнопка [image] - добавляет новую семью, если никакая не была подключена ранее, и добавляет в неё конкретного родителя (отца или мать, в зависимости от выбранной секции), кнопка [image] соответственно отсоединяет из присоединенной к человеку семьи выбранного родителя (отца/мать). Также возможны быстрые переходы на записи родителей по кнопкам [image].

and in English localization like this:

> * The same buttons: [images] located under the name of each parent perform other functions. [image] button adds new family if one was not added already, and then adds the concrete parent to this family (father or mother, depending on the selected section). [image] button removes a parent (father or mother) from person's family. To quickly jump to a parent's person record you use [image] button.
