### ISSUE TITLE
Upper Caps Issue in Saved GEDCOM... 

### ISSUE THREAD

**Issue by Ibuprophen** [Serg-Norseman/GEDKeeper#352]
I'm not sure if this is an issue or a setting I can't locate, but I'll try to explain this simply... 

When I save a GEDCOM file, I had noticed that dates that were formatted like "1 Jan 2022" beforehand (that I prefer) were saved as "1 JAN 2022". 

I just prefer not to yell/scream the month... LOL! 

Thank you very much for your time and understanding with this... :-)) 

~Ibuprophen 
[Theoretical Theorist]

**Comment by Serg-Norseman** [comment]
The uppercase months inside the GEDCOM file are part of the standard. In the current version of the program kernel, I cannot read data from a GEDCOM file and write service data exactly as they were before - I write as specified in the standard.

At least the key features of the GEDCOM format, I try very hard not to deviate from the standard.

**Comment by Ibuprophen** [comment]
Isn't there an option that can be provided for those who choose to keep the format of dates/text as it is? 


~Ibuprophen

**Comment by Serg-Norseman** [comment]
After reading the file, the data is stored in RAM in the form of codes - to save memory. There is no way to keep the original appearance of identifiers. Therefore, the option to preserve the original format is not possible in this case.

**Comment by Ibuprophen** [comment]
Thank you very much for explaining this @Serg-Norseman! :-)) 

I found a (long way) to change this via a 3rd party software I typically use for something totally different than this. LOL! 

Keep up the GREAT work! 👍 


~Ibuprophen
