### ISSUE TITLE
request:  In a new or existing record to make each name/word and surname/word in a capital letter after the first name/word?

### ISSUE THREAD

**Issue by DuckG** [Serg-Norseman/GEDKeeper#378]
Example: 
now: 
Vladimir vladimirovitsj sergejevitsj maria 

new:
Name:
Vladimir Vladimirovitsj Sergejevitsj Maria

**Comment by Serg-Norseman** [comment]
1) Menu Service \ Options \ Interface tab \ All lists subtab \ "First capital letter in names" option
2) In the name input field, press the Ctrl + Down buttons - this will format the name. However, this only works with the first name on the line. The second and subsequent ones will remain the same.

I'll consider extending the name formatter to handle the second and subsequent parts.
