### ISSUE TITLE
Request: is it possible make in the tab individuals besides a column 'Full name' a seperate column with 'Name' and a seperate column with Surname and a column with Nickname?

### ISSUE THREAD

**Issue by DuckG** [Serg-Norseman/GEDKeeper#379]
Adding three columns in the tab Individuals: 
Surname, Name and Nickname.

**Comment by Serg-Norseman** [comment]
Menu Service \ Options \ Interface tab \ List of Individuals subtab \ Check Nickname column.
Menu Service \ Options \ Interface tab \ All lists subtab \ Name format in lists - for select subcolumns of name parts.
