### ISSUE TITLE
Калькулятор родственных связей ошибается на уровень.

### ISSUE THREAD

**Issue by se-sss** [Serg-Norseman/GEDKeeper#402]
Братьев считает правильно.
Двоюродных считает правильно.
Для троюродных в качестве троюродного берёт родителя троюродного, а не самого троюродного.

V2.20.1.0

**Comment by Serg-Norseman** [comment]
Спасибо! Обязательно посмотрю и попробую исправить к следующему выпуску (2.21).

**Comment by se-sss** [comment]
2.21.0.0
Сломалось совсем
![image](https://user-images.githubusercontent.com/440601/187543220-7f872a71-a3ae-4b6a-8646-66530066ed04.png)

**Comment by se-sss** [comment]
Подставляет мать 2-го человека, А родство вроде правильно.

**Comment by Serg-Norseman** [comment]
Проверю

**Comment by Serg-Norseman** [comment]
Не могу воспроизвести. Приведите скриншот дерева с включенным отображением отношений и выделенным неправильным, чтобы было понятно о чем речь.

**Comment by syerokhin** [comment]
![image](https://user-images.githubusercontent.com/65550538/187688933-965fc7d0-4618-4bc8-9de7-2187c18e90fa.png)

**Comment by se-sss** [comment]
![image](https://user-images.githubusercontent.com/440601/187688761-b9763d21-d595-4f2e-8009-6e04f2511738.png)

**Comment by se-sss** [comment]
То есть, да, сестра, но подставляется мать.
На троюродных аналогично.
Вообще сразу после фикса я сам собирал из исходников и работало.
А релиз - нет

**Comment by Serg-Norseman** [comment]
Проверил на нескольких похожих семьях у меня в базе, пока никак - ни в релизе, ни в рабочем проекте :(

**Comment by se-sss** [comment]
[Неизвестно.ged.zip](https://github.com/Serg-Norseman/GEDKeeper/files/9551377/ged.zip)
Сделал простенький файл.
Сразу после добавления братья правильно определялись.
После сохранения и перезапуска программы - неправильно.

И снова сама связь считается правильно, а вместо 2-го человека берётся его мать.
![image](https://user-images.githubusercontent.com/440601/189745773-73652843-bd9f-4022-99e8-10bc0a12a6f0.png)

**Comment by se-sss** [comment]
родители A и A(F), дети AA и AB

**Comment by se-sss** [comment]
[fix_relations.patch.txt](https://github.com/Serg-Norseman/GEDKeeper/files/9551679/fix_relations.patch.txt)

Я шарпы ек  особо знаю. Но вроде так работает.

**Comment by se-sss** [comment]
Но непонятно, почему при изначальном создании работало правильно.

**Comment by Serg-Norseman** [comment]
Да, баг подтвержден, повторимость есть.
Занятно - в прошлом алгоритм имел похожую часть, как вы добавили. Может не в точности, но что-то похожее. Нужно будет поднять историю коммитов и посмотреть как выглядело и понять - почему я это "соптимизировал".

**Comment by Serg-Norseman** [comment]
Вы молодец :) и в коде разобрались, и патч сделали. Серьезный подход, уважаю! 👍

**Comment by Serg-Norseman** [comment]
> Но непонятно, почему при изначальном создании работало правильно.

Мне еще больше непонятно, почему при неработающем калькуляторе эта же самая ситуация на том-же файле в древе выдает правильный результат.

**Comment by se-sss** [comment]
Могу предположить, что нисходящая ветка родства для калькулятора заполнятся по другому.
То есть ребра те же самые в том же порядке, но каждое отдельное ребро перевернуто.
И тут код адаптировано под перевернутое ребро, а подсунули неперевернутое. 
a-b, b-c, c-d и b-a, c-b, d-c. 
Бралось последнее ребро, но не конечная точка.

**Comment by Serg-Norseman** [comment]
Я проверил ваш патч в работе, всё хорошо работает. Каких либо проблем не заметил. И код нормальный. 
Вы можете сделать коммит и PR от себя? Я бы хотел, чтобы ваше участие было в истории :)

**Comment by syerokhin** [comment]
А теперь задача с звёздочкой. :-)
Родство через жену
![image](https://user-images.githubusercontent.com/65550538/189995401-16afc939-bcfa-4c61-85f6-8ef5733cbbb9.png)

**Comment by se-sss** [comment]
Кажется работает.
Немножко странно выглядит, что начинается рассказ не с перевого выбранного, но так изначально было (см первый скриншот выше),

![image](https://user-images.githubusercontent.com/440601/190010704-59e24807-3557-4e87-8856-53a4105ad312.png)

**Comment by Serg-Norseman** [comment]
Ужас! Вот это круто! На таких примерах я не тестировал, да. Вы меня повергли в нокаут с такими экспериментами :)

**Comment by se-sss** [comment]
А задача с 3-мя звёздочками - искать разные пути и их тоже выводить.
Но эту багу наверное надо закрыть.
