### ISSUE TITLE
Feature: Поиск родственников для выбранного человека по критерия родства

### ISSUE THREAD

**Issue by se-sss** [Serg-Norseman/GEDKeeper#404]
Сейчас калькулятор работает только для для выбранных 2-х человек.

Хотелось бы иметь возможность выбрать человека и получить для него список всех
n-юродных братьев и сестёр (n - выбранное натуральное число).

Неплохо бы поддержать и другие критерии, если есть чёткое понимание кто это (двоюродные дяди, например.)

**Comment by Serg-Norseman** [comment]
Вы именно список хотите?
Сейчас, если включить опцию показывать степени родства в настройках отображения дерева и вывести дерево - там у каждого человека будет отображаться его степень родства относительно центральной персоны. При этом, есть возможность менять "точку отсчета" по кнопке F7 или через всплывающее меню на заданной персоне.

Не вполне понятен практический смысл такой функции. Объясните?

**Comment by Serg-Norseman** [comment]
Еще, на будущее, пожалуйста пишите на русском языке в группу программы в Телеграмме. Там и обсудить оперативно можно и какие-то нюансы в личку можно перевести. А здесь так делать не нужно.

**Comment by se-sss** [comment]
I just  think that might be interesting (Like windows with statistics you have.).
Sorry, no telegram available. And it demands phone number for registration making chance it will appear on my computer miserable.
