### ISSUE TITLE
GKv2: Settings window truncated

### ISSUE THREAD

**Issue by Flexmaen** [Serg-Norseman/GEDKeeper#407]
![bug_gedkeeper](https://user-images.githubusercontent.com/6330276/190268138-4fd4b5b3-f820-4ab7-936d-489b875f64be.png)

Windows with settings are truncated in some resolutions.
As workaround you could try to use the TAB-key to get the focus at the invisible buttons.
However, that will need a fix.

Window did not work with 1920x1080 and font size 150%. It does work with 1680x1050 and font size 100%.

**Comment by Flexmaen** [comment]
Isn't this rather a bug? You cannot change any settings if the window is too big.
As a skilled user you might be able to find the invisible button with your keyboard but I guess most users just will go for the X button and close the window and cancel their changes.
Maybe it helps not to lock the window borders.

By this chance I also discovered that the TAB order of the checkboxes is a bit messed up, but that's not really an important issue.

**Comment by Serg-Norseman** [comment]
To solve this problem well / reliably - we need to reorganize the entire dialogue. Because it is constantly growing and a different layout of options has long been needed, more flexible, possibly more tabs.
