### ISSUE TITLE
Event data mask problem

### ISSUE THREAD

**Issue by me0607040211** [Serg-Norseman/GEDKeeper#410]
![image](https://user-images.githubusercontent.com/28685171/192213850-f9e01514-8dee-49aa-b239-faa571efcbf9.png)
![image](https://user-images.githubusercontent.com/28685171/192214048-75d6660b-9bfa-4791-8737-e136bf6e928e.png)

**Comment by Serg-Norseman** [comment]
What is your locale (region-language) and date format regional settings? Add screenshot please

**Comment by me0607040211** [comment]
![image](https://user-images.githubusercontent.com/28685171/192407647-17887e7a-4697-49fd-a5cb-1d3e11ac18bf.png)

![image](https://user-images.githubusercontent.com/28685171/192407586-373ce120-5a0d-4c50-8145-6c508cefdf7a.png)

**Comment by tyrfing666** [comment]
I have a similar problem entering dates.
![Clipboard01](https://user-images.githubusercontent.com/12942583/194733924-15b05f51-799b-4e99-991f-5633013d32e3.jpg)
![Clipboard02](https://user-images.githubusercontent.com/12942583/194733925-b42cadd9-2ca7-4f08-8cbd-40bd5c3a31ae.jpg)
![Clipboard03](https://user-images.githubusercontent.com/12942583/194733976-be3d7635-1259-467b-a9db-2e9f77e7fc22.jpg)

**Comment by tyrfing666** [comment]
I went into the GED file and changed the date to "04 JAN 1965" and it worked - it shows up as "04/01/1965" in the entry for the individual.
So it's a problem with the data entry dialog.
