### ISSUE TITLE
Initial language to run on systems without the Russian language

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#42]
Make a determination of the presence of application's languages in the system, if this languages do not exist - just switch English.

**Comment by ruslangaripov** [comment]
> determination of the presence of application's languages in the system

What does this mean? Do you want to check OS localization? Keyboard layout? Regional settings?

Say I have no Russian language. But I have used it in the last application session I run GK. Would GK reset application language to English each time it starts up?

What if I have forced **a language** missing in my operating system? What will happen then?

**Comment by Serg-Norseman** [comment]
I don't know yet. It is assumed that the language detection will be triggered only at the first launch after installation when the configuration file has no corresponding parameter. The first case is to search the installed languages. And second case: when you first start to give special selection dialog so the user was not looking for options dialog on foreign language.

**Comment by ruslangaripov** [comment]
> to give special selection dialog so the user was not looking for options dialog on foreign language

:+1:

I'll bet my life you'll get :+1: for user experience here!

**Comment by Serg-Norseman** [comment]
Long implemented the simple solution.
