### ISSUE TITLE
`GetTempDir()` is not quite multi-platform

### ISSUE THREAD

**Issue by danfe** [Serg-Norseman/GEDKeeper#451]
On Windows, it's probably safe to assume that `TEMP` environment variable is always there and set, but on Unix-like systems it is not, and when it is, it's typically named `TMP`.  Consider the following patch:
```patch
@@ -1758,7 +1758,11 @@
 
         public static string GetTempDir()
         {
-            string tempPath = Environment.GetEnvironmentVariable("TEMP");
+            string tempPath;
+            if (SysUtils.IsUnix())
+                tempPath = Environment.GetEnvironmentVariable("TMP") ?? "/tmp";
+            else
+                tempPath = Environment.GetEnvironmentVariable("TEMP");
             return tempPath + Path.DirectorySeparatorChar;
         }
```

**Comment by hazzik** [comment]
More correct and cross-platform way would be to use [`Path.GetTempPath()`](https://learn.microsoft.com/en-us/dotnet/api/system.io.path.gettemppath)
