### ISSUE TITLE
invalid version in the release tar ball

### ISSUE THREAD

**Issue by blshkv** [Serg-Norseman/GEDKeeper#456]
The latest version was released tagged as v2.25.2. However, there are few files has been generated as 3.1.0-1. 
A minor thing, but my script failed to download it automatically. Please keep it in sync.

**Comment by Serg-Norseman** [comment]
The file versions are correct. The next several (approximately 2: 2.6/3.2 and 2.7/3.3) releases will come out simultaneously in two directions: legacy - versions 2.X and new generation based on dotnet6 - versions 3.X. They have a common core, independent of the .NET variant, but the client UI layer is on different frameworks and different UI bases, so I cannot separate them in any other way. When the direction 3.X reaches the required level of readiness - legacy will be frozen and releases will stop.

Which script is not working for you? Under what OS are you generating the package?

**Comment by Serg-Norseman** [comment]
Theoretically, I can do it differently: freeze the numbering of versions 2.X and then go straight to 3.X - because there will be no new non-Windows versions of 2.X.
