### ISSUE TITLE
[GKv3] Split unit test assemblies into Core and UI tests

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#470]

**Comment by Serg-Norseman** [comment]
I couldn't get NUnit tests to work in VS 2022. To do this, I also have to keep VS 2019. This is inconvenient :(

**Comment by Serg-Norseman** [comment]
If I managed to get the NUnit Adapter into VS 2022 in any way, the transition can be canceled. I don't need it. Although NUnit seems to stop developing, and this is also a motive.

**Comment by hazzik** [comment]
Likely, you need to install NUnit3TestAdapter 4.3.0 or above

**Comment by Serg-Norseman** [comment]
Install without VS Manage Extensions? ok, I'll try

**Comment by Serg-Norseman** [comment]
This nuget is implied, as I understand it. And if the solution is maintained in its pure form without nuget dependencies?

**Comment by hazzik** [comment]
> And if the solution is maintained in its pure form without nuget dependencies?

xUnit will likely require the same nuget dependencies 

However, you can use it as just a library: https://github.com/nunit/nunit3-vs-adapter/releases/tag/V4.5.0

**Comment by Serg-Norseman** [comment]
I have included NUnit3TestAdapter 4.5.0 as a link. `Test Explorer` shows 713 tests, but the `Run All Tests` button builds and nothing further happens, no tests are executed.

**Comment by Serg-Norseman** [comment]
Replaced the reference with the nuget package.
The result is negative.

**Comment by Serg-Norseman** [comment]
2e622efd1fb50effaeeadc0d84ffafffa02f2d75
