### ISSUE TITLE
cousin of wife - is it correctly named?

### ISSUE THREAD

**Issue by syerokhin** [Serg-Norseman/GEDKeeper#474]
Файл:
[Sample.zip](https://github.com/Serg-Norseman/GEDKeeper/files/11900124/Sample.zip)

Not sure relation is correctly named.

двоюродный брат (GS - grand son) жены ( GD grand daughter) по отношению   к мужу

Точно зять это?
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/65550538/ecd680ad-3e7c-4a1f-b9ad-886ac4b1159e)

В обратную сторону без вопросов
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/65550538/0179a12c-5563-4569-b9a3-9e3010f578ed)

И, конечно,
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/65550538/b1440b32-06e8-4401-8a10-76d1c285266b)
(Но у нас кузенами не называют)

**Comment by syerokhin** [comment]
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/65550538/33ab5792-081e-4737-b061-5b88789dd8ad)

**Comment by hazzik** [comment]
> Точно зять это?

Двоюродный зять будет правильное наименование, вот картинка из [Википедии](https://ru.wikipedia.org/wiki/Родство#Двоюродные):

![image](https://github.com/Serg-Norseman/GEDKeeper/assets/144791/d5340ff7-a008-409d-893a-9f60a080e900)

Муж двоюродной сестры -- двоюродный зять.

**Comment by syerokhin** [comment]
Мне первым попалось утверждение, что это двоюродный деверь.
Но вики более солидный источник всё же, хотя и не на 100%.

**Comment by hazzik** [comment]
> Мне первым попалось утверждение, что это двоюродный деверь.
 
Вот что [Википедия говорит](https://ru.wikipedia.org/wiki/Родство#Супруг(а)_близкого_родственника):

> Двоюродный брат мужа для жены — двоюродный деверь.

Если M и GD поменять полами, то GS будет двоюродный деверь.
