### ISSUE TITLE
Incorrect relation calculated

### ISSUE THREAD

**Issue by se-sss** [Serg-Norseman/GEDKeeper#478]
[Sample.zip](https://github.com/Serg-Norseman/GEDKeeper/files/11946825/Sample.zip)

Check KKKKKKK and MMMMMM

![image](https://github.com/Serg-Norseman/GEDKeeper/assets/440601/46125487-4e41-4331-9436-88428a4669a0)

![image](https://github.com/Serg-Norseman/GEDKeeper/assets/440601/0fb71277-d1a8-4920-ab65-52a242efb67e)

**Comment by se-sss** [comment]
curRel=rkSon  prevRel=rkWifeFather  prevprevRel=rkWife  finRel=rkBrotherInLaw_W

**Comment by Serg-Norseman** [comment]
I found the problem, it is not in this algorithm at all and not even in GK. In 3-4 hours, as soon as possible, I will make commits.

The problem is in the EnumSet class from my BSLib library. Although the class is designed for ulong (64bit), mistakes were made in a couple of places and the maximum fit was 32bit. Because of this, and also because of recent improvements with the replenishment of types of relationships, some of them no longer fit in the container. I was lucky - I introduced two new rules to detail the current situation and was very surprised when I found that they did not work at all. Then it got easier...

**Comment by Serg-Norseman** [comment]
Have you checked? Does it work correctly in your case or is it still wrong?

**Comment by se-sss** [comment]
I have 
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/440601/2e86b9cc-fa89-4aa9-8352-1fa8e93ceb70)
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/440601/e50db5eb-a18d-4257-82b7-486fd250ca02)

**Comment by se-sss** [comment]
KKK - племянник F, А жека MMMM я бы ожидал

**Comment by se-sss** [comment]
Так выдаёт старая версия
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/440601/5ee00117-ade6-4c7a-af85-a4dd39e1c005)
И это правильно

**Comment by Serg-Norseman** [comment]
But according to the definition, an aunt's husband is an uncle, even if not his own, so I did it

**Comment by Serg-Norseman** [comment]
I'm afraid that the difference in the perception of definitions will constantly create problems)))

**Comment by se-sss** [comment]
Probably. Never heard idea that husband of aunt is also  my uncle.

**Comment by se-sss** [comment]
А на улице так половина прохожих - дяди

**Comment by Serg-Norseman** [comment]
> Probably. Never heard idea that husband of aunt is also my uncle.

Wiki. And in my family, the husband of my own aunt was an uncle, and I was his nephew. At least in everyday communication.

**Comment by se-sss** [comment]
Вообще, по хорошему эта штука должна подлежать ещё и локализации.
Я как-то раз пересекался с китайцем в универе.
У них там, например, брат старший и брат младший - это принципиальная разница и разное слово.

**Comment by Serg-Norseman** [comment]
Постепенная работа в этом плане идет. Недавно, например, для локализации на исландский были разделены пресловутые дяди и тети: как мне сообщили, обобщенные слова в исландском есть конечно, но нативными являются раздельные термины брат/сестра матери/отца. Вчера вот ввел дядя/тетя как муж тетки/жена дяди. Если такие неродные термины плохо применимы, в локализации их можно детализировать. Вот племянник/племянница всё равно останутся как есть.
