### ISSUE TITLE
Incorrect interpretation of time periods

### ISSUE THREAD

**Issue by cbettinger** [Serg-Norseman/GEDKeeper#479]
As you can see in the screenshots below a fact with its date starting with _TO_ gets interpreted as a period of time starting _FROM_ the given date instead of _TO_ the given date.

![date-to](https://github.com/Serg-Norseman/GEDKeeper/assets/18167176/3d3e05ef-740e-480b-a5c8-de4c50313ef8)

![period-from](https://github.com/Serg-Norseman/GEDKeeper/assets/18167176/22b3ce6c-35fb-42e2-b509-174920e51f23)

I did not test it but i could image that this bug also manifests vice versa, meaning a _FROM_ date gets interpreted as _TO_ date.

**Comment by Serg-Norseman** [comment]
Thanks for finding the bug!
