### ISSUE TITLE
Add support for _FSFTID tag

### ISSUE THREAD

**Issue by hazzik** [Serg-Norseman/GEDKeeper#490]
RootsMagic adds `1 _FSFTID ABCD-XYZ` tag to people matched to FamilySearch.org tree. It would be nice to provide a link to the site similar to #438. Either with transformation to RFN tag, or directly. The link format is https://www.familysearch.org/tree/person/ABCD-XYZ

**Comment by Serg-Norseman** [comment]
I think it needs to be converted to RFN. Can there be a situation when the record already has an RFN and what to do in this case. Overwrite or leave a few contrary to the standard?
