### ISSUE TITLE
Create makefiles

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#5]
Create makefiles to build the project without IDE.

**Comment by ruslangaripov** [comment]
:+1: for the idea!

I can create Makefile for ported GNU make (the make utility for MSYS2/MINGW). But I believe it will work with Linux's native make seamlessly :smiling_imp: Of course, once we've provided correct tools settings.

**Comment by Serg-Norseman** [comment]
I admit that I never figured out how to compile C# projects without the IDE. Now gradually trying to figure out how it all works. At least under Windows for beginning. Today started with the fact that in spare times cleaning out the project files from the rubbish (configuration/platform and other).

**Comment by ruslangaripov** [comment]
In my time I had started with the same stuff :laughing: 

As far as I know there's 'csc.exe' (**C**-**s**harp **c**ompiler) which is run by msbuild. And that's all I know about how C# builds code :laughing: 

If 'csc' is the only tool used to build a C# project, we must give to him correct switches and that's all!

**Comment by ruslangaripov** [comment]
*Source code language stats*: ...  Makefile 2.9% ... :smiling_imp:

**Comment by Serg-Norseman** [comment]
I'm not thoughts about it. Forget.
Ok, again open :)

**Comment by Serg-Norseman** [comment]
There is no need for actualization, the question is frozen until future tasks.
