### ISSUE TITLE
Faulty installation file?

### ISSUE THREAD

**Issue by cbettinger** [Serg-Norseman/GEDKeeper#509]
Recently I wanted to update my installed GEDKeeper version to 2.28.1 using the setup file shown in the screenshot below.

Unfortunately this setup file seems to install version 2.28.0. This version number is shown the in file properties, the about dialog and the update request message that appears at startup (see screenshot).

![version](https://github.com/Serg-Norseman/GEDKeeper/assets/18167176/4cdc69c2-46ee-4135-b97b-53c79bbee027)

**Comment by Serg-Norseman** [comment]
Apparently, when creating a minor release, an error was made in the version number.
