### ISSUE TITLE
Residence event without value

### ISSUE THREAD

**Issue by cbettinger** [Serg-Norseman/GEDKeeper#510]
Today I noticed that I cannot save events of type residence without entering a value anymore. Previously it was no problem to leave the value field empty and just add a location ("Trier (Zeughausstraße 109)" in the example below).

I am using version 2.28.0 or 2.28.1 (see #509).

![location](https://github.com/Serg-Norseman/GEDKeeper/assets/18167176/16c15886-c67f-42d4-b013-acfca3e7ba5b)

**Comment by Serg-Norseman** [comment]
The inability to store facts without values was introduced to be more consistent with the standard. I myself doubt this decision... Perhaps it was done in vain.

**Comment by cbettinger** [comment]
Could you cite the part of the GEDCOM specification that requires a non-null event value?

I can find several examples in the 5.5.1 specifiation that demonstrate, that there is no need for a event value:

Page 21:

> 1 EVEN
> 2 TYPE Awarded BSA Eagle Rank
> 2 DATE 1980

Page 75:

> 1 RESI
> 2 ADDR 73 North Ashley
> 3 CONT Spencer, Utah UT84991
> 2 DATE from 1900 to 1905

**Comment by Serg-Norseman** [comment]
I looked at the standard. I probably misunderstood page 33 (item RESI).
