### ISSUE TITLE
Empty lines in notes

### ISSUE THREAD

**Issue by cbettinger** [Serg-Norseman/GEDKeeper#522]
I recognized that GEDKeeper swallows empty lines in notes. For example this note

![emptyline](https://github.com/Serg-Norseman/GEDKeeper/assets/18167176/e943654f-ec24-41bf-8148-d1c9e397b78a)

gets stored as

```
0 @N1@ NOTE   
1 CONT A   
1 CONT B   
1 CONT C   
...
```
and therefore when the note is re-opened it is displayed like this:

![emptyline2](https://github.com/Serg-Norseman/GEDKeeper/assets/18167176/95056d9e-33aa-4ae6-9557-45959238badb)

I am not quite sure if the GEDCOM specification prohibits empty lines. If not it would be great to store empty lines as they are.

**Comment by burtek** [comment]
@Serg-Norseman Was the change in copyright dates from 2021 to 2023 intentional? Asking as we have 2024 already 😅

**Comment by Serg-Norseman** [comment]
I've worked hard )))))) Eyes can't see, fingers can't type )))

Then I'll fix it somehow :)
