### ISSUE TITLE
On linux, can't see Reports menu options

### ISSUE THREAD

**Issue by burtek** [Serg-Norseman/GEDKeeper#525]
On linux, can't see Reports menu options, regardless of theme/dark mode
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/2940958/bc0bf093-33ab-4224-b23b-24c3930795bd) ![image](https://github.com/Serg-Norseman/GEDKeeper/assets/2940958/923af200-8510-49d9-a19c-c69d99b1174a)

Other menus display correctly.

[gedkeeper.webm](https://github.com/Serg-Norseman/GEDKeeper/assets/2940958/9c5279a9-189f-4b7d-968d-6cd2ad841f9b)

LMDE6
Cinnamon 6.0.4
GedKeeper 3.4.0.0

**Comment by Serg-Norseman** [comment]
I can’t reproduce it yet in the distributions that I have available.

**Comment by burtek** [comment]
Let me check if it's not an issue with cinnamon themes or cinnamon itself
then.

pon., 29 sty 2024, 15:43 użytkownik Sergey Zhdanovskih <
***@***.***> napisał:

**Comment by Serg-Norseman** [comment]
No, I think there is some actual glitch with this particular menu. But it just doesn’t reproduce for me at all. I'll think about how else to catch him...

**Comment by burtek** [comment]
The question I guess is what's different about this menu, compared to
others, that would make a difference here?

pon., 29 sty 2024, 19:30 użytkownik Sergey Zhdanovskih <
***@***.***> napisał:

**Comment by Serg-Norseman** [comment]
I'm planning a new release on February 14, then it will be possible to check how the current edit worked.

**Comment by Serg-Norseman** [comment]
Released a new version. Is the problem still there or has it gone away?

**Comment by burtek** [comment]
Works correctly now.
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/2940958/dca52a0d-998f-4359-85dd-0118585ac5d7)
