### ISSUE TITLE
An error in translation for "Relationship Calculator" {bug}

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#53]
The picture below shows the issue (found on test database '-rus-nobles.ged'):

![default](https://cloud.githubusercontent.com/assets/16339987/18636621/edb630f4-7ea2-11e6-8e44-8ea5be14aa7c.PNG)

I believe 'I1' and 'I4' titles are also errors (both are seen on thescreenshot).

**Comment by ruslangaripov** [comment]
:+1:

**Comment by Serg-Norseman** [comment]
In this case, only a wrong translation, but also to other lot of problems

**Comment by ruslangaripov** [comment]
Sure. I believe all that problems rise from Russian names of relations. There's no one-to-one translation here between English and Russian words, is it? I suppose this is a stuff for your culture-related framework :smiling_imp:

**Comment by Serg-Norseman** [comment]
I don't know yet... until the main goal - long chains between the branches

**Comment by Serg-Norseman** [comment]
Fixed by 6fb486fe613ef119d9001076971920347ef6e793
