### ISSUE TITLE
Android (beta) feedback

### ISSUE THREAD

**Issue by burtek** [Serg-Norseman/GEDKeeper#532]
Not sure if/how well the android package should be working at this point, but since you released it and pointed it out in release notes, I'm gonna assume it's supposed to have at least basic features working.

On my device (Samsung Galaxy S20 FE running Android 13) the app doesn't work at all. Sometimes it gets stuck on splash screen, but if it gets past the splash screen I end up staring at a white screen.

Feel free to close if you don't need this feedback, just figured you'd probably want to learn how it works on someone else's device.

**Comment by Serg-Norseman** [comment]
The latest release build for Android is obviously glitchy. Withdrew this package from publication.

**Comment by Serg-Norseman** [comment]
I tested it the day before - everything was normal. I'll look for what went wrong.

**Comment by Serg-Norseman** [comment]
I uploaded a new build of the Android version everywhere. The previous one was the wrong build.

For it to work properly, it is better to delete the previous installation manually, without relying on a correct update (the version number has not changed).

**Comment by burtek** [comment]
Play Protect is not happy about the .apk but it looks like it's working now

**Comment by Serg-Norseman** [comment]
So that the security systems do not swear anywhere, I need a good digital signature. I don't have the opportunity to do this right now.
