### ISSUE TITLE
Feature request: Add option to distinguish not registered marriages in the family tree view

### ISSUE THREAD

**Issue by burtek** [Serg-Norseman/GEDKeeper#537]
There are 3 options for marriages: registered, not registered and divorced. Divorced families are already distinguished by different spouse colors, which can be set in the config dialog. There should be an option to distinguish not registered marriages too. I'd suggest using dotted line, similar as for foster kids.

I'd like this to be an option, because not everyone might want this to be visible on the family tree.

**Comment by burtek** [comment]
I think you might have misunderstood me. I was talking about not registered marriages, not divorced. Divorced are already marked by different spouses colors...

**Comment by Serg-Norseman** [comment]
Hm... )))))
