### ISSUE TITLE
I18n: Incorrect capitalization

### ISSUE THREAD

**Issue by fullben** [Serg-Norseman/GEDKeeper#541]
Event type in "links" section of "Locations" tab in the German version contains incorrectly capitalized nouns.

# Environment

- Microsoft Windows 10.0.19045.4046
- GEDKeeper 3.5.0.0, non-portable version

# Steps to Reproduce

1. Open a `.ged` file that contains at least a person with an associated event and a location associated with that person.
2. Go to the "locations" tab and select the location, then view the location info that will appear on the right side, specifically the "Links" section.

## Actual Behavior

The associated person will be listed as follows: `Müller Bruno, geburt` (Müller Bruno, birth)

This happens for all event types.

## Expected Behavior

The associated person should be listed as follows: `Müller Bruno, Geburt` (Müller Bruno, birth)

The event type should start with an uppercase letter, since in German, nouns always start with an uppercase letter.

# Other

I'm creating a new issue for this, since I'm suspecting this might not actually be related to internationalization, but just some *to lower case* call somewhere in the code.

**Comment by Serg-Norseman** [comment]
Yes, in this case I am using the lowercase function for a word with a capital letter.

**Comment by fullben** [comment]
I see. FYI, I found that there are other occurrences of this behavior - for example, the links of sources.

**Comment by fullben** [comment]
Although I'm assuming it's gonna be the same part of the code, even if its a different part of the UI... :)
