### ISSUE TITLE
Blurry photos in tree views

### ISSUE THREAD

**Issue by fullben** [Serg-Norseman/GEDKeeper#543]
All portrait images appear blurry in the tree views.

# Environment

- Microsoft Windows 10.0.19045.4046
- Display: 2560 x 1440, 125% Scaling
- GEDKeeper 3.5.0.0, non-portable version

# Behavior

All portraits I add for any person are blurry in the tree view, see screenshot below (names are blurred out on purpose).

![image](https://github.com/Serg-Norseman/GEDKeeper/assets/74531112/6bfb6911-c142-413c-9c5a-1bc0e5608bf8)

Images in question (PNGs) have the following resolutions:

- 2658 x 3771
- 1766 x 1170

Images have been added as multimedia entry with:

- Type *photo*
- Store type *Saving to the store*

# Other

Also, what I personally find a bit irritating is the fact that instead of showing a cropped version of the linked image, the tree view always displays a thumbnail of the full image.
I'd prefer having the option to have all portraits shown in the tree view to have the exact same size & aspect ratio, but that's probably a new feature request, beyond the scope of the issue I'm experiencing 😄

**Comment by Serg-Norseman** [comment]
I've dealt with this issue in the past and created some workaround recommendations for a group of users. But due to the lack of organized technical support, I can’t now remember how it all ended.

I’ll try to look in the correspondence to find out what happened then. I have the impression that this was due to incorrect processing of some very large photographs that were fully included as portraits.

When specifying a portrait image, did you specify the exact area of the portrait? You are sure that the full image is used in the tree if there is a selected area when linking?

**Comment by fullben** [comment]
Ah I see. This has been a user error, at least partially. I wasn't aware that I had to select an area of the photo when setting a profile picture for an individual.

The blurry thumbnail/portrait seems to occur whenever I don't specify an area of the photo to be used as profile photo in the "Choice of portrait" window.
With no area specified, the preview of the portrait in the persons/individual's overview will be fine, but the tree views will render the pixelated version of the portrait.

Maybe there could to be some sort of validation/bug fix to prevent this?
Also, to me it wasn't really clear what I was meant to do when being presented with the "Choice of portrait" window. Maybe this could be improved by adding some new UI text at the top of the window, above or next to the zoom options?

Furthermore, I would really appreciate being able to restrict the selection box to a certain aspect ratio, so that I can create all my portraits with the same dimensions 😄

**Comment by Serg-Norseman** [comment]
Great ideas! I will think.

I can't do it quickly. Validating the user's choice of photos is a difficult topic for me. And in order for the selection area to be proportional, I will first have to make a selection rectangle with a changeable border without selecting a new one.
