### ISSUE TITLE
Suggestion: show number of sources/notes/multimedia rather than just "+"

### ISSUE THREAD

**Issue by burtek** [Serg-Norseman/GEDKeeper#544]
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/2940958/3ce19182-e687-4a4c-88e6-d20b7a6d02fe)

Is there a way to show count of sources/notes/multimedia rather than just a "+" sign? The column would stay empty if there are no sources/notes/multimedia (just as it does now), but if there are, it would show a number (1, 2, etc)

**Comment by Serg-Norseman** [comment]
It will be necessary to create an option to switch between modes, because it is more convenient for me when only the fact of availability is noted, and not the quantity.
