### ISSUE TITLE
Cancelling input clear the field in "Relationship Calculator" {unwanted behavior}

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#55]
There's an unwanted behavior (in my opinion) in "Relationship Calculator". After I've closed person picker, the related text field becomes clear. Let me explain.

I open the "Relationship Calculator" and set some values:

![default](https://cloud.githubusercontent.com/assets/16339987/18637547/3934c6be-7ea6-11e6-8b48-54589abd7e54.PNG)

Now I decide to select another person on the second field...

![default](https://cloud.githubusercontent.com/assets/16339987/18637606/600d1e08-7ea6-11e6-92f4-b86e9792f18f.PNG)

...but I changed my mind and click "*Cancel*" or just close the person picker. This is what I get:

![default](https://cloud.githubusercontent.com/assets/16339987/18637654/8fd4435a-7ea6-11e6-8dff-726c32d15eb7.PNG)

I've lost the name. I believe the "previous" value must remain. Correct me, if I'm wrong.

And please make "*Kinship*" field read-only :smiling_imp: One shouldn't be able to change that text.

**Comment by ruslangaripov** [comment]
Are field names like "I1" and "I2" (see my screenshots above) by design? If yes, what does "I" mean in this case?

(Very fast fix by the way :+1: )

**Comment by Serg-Norseman** [comment]
No :) This is a temporary stub for ease of debugging. Will soon be removed under appropriate directives.

**Comment by ruslangaripov** [comment]
I got it :smiley:

**Comment by Serg-Norseman** [comment]
And I1, I2...I<N> is the standard notation for keys of individual records in the gedcom format. First column from table of individuals - it's id of record without "I" (Individual, F/amily, N/ote, S/ource, R/epository and etc).

**Comment by ruslangaripov** [comment]
Thanks for detailed explanation! :+1:
