### ISSUE TITLE
User defined name type

### ISSUE THREAD

**Issue by cbettinger** [Serg-Norseman/GEDKeeper#550]
The GEDCOM specification (https://gedcom.io/specifications/ged551.pdf, page 56) allows user defined types of names:

> NAME_TYPE:= [ aka | birth | immigrant | maiden | married | \<user defined\>]
> ...
> user_defined= other text name that defines the name type.

 IMO the following structure is completely ok:

```
0 @I1@ INDI
1 NAME Max /Mustermann/
2 SURN Mustermann
2 GIVN Max
2 TYPE adoption
```

Unfortunateley, GEDKeeper deletes TYPE-lines that do not have a value GEDKeeper knows (e.g. **2 TYPE adoption**).

**Comment by Serg-Norseman** [comment]
There may be problems here :(
