### ISSUE TITLE
Suggestion: Frequency of names report: Consider surnames in male and female forms as same

### ISSUE THREAD

**Issue by burtek** [Serg-Norseman/GEDKeeper#552]
There is a rule in polish language that if the surname ends with -cki/-ski/-dzki, it changes into -cka/-ska/-dzka for females. Not sure if any other language has something like this, but I guess it would be nice to be able to specify such rules for the report generator.

My idea is a list of "surname replacements" for the report generation. In this case, before the report generation (in app settings?), I could provide following replacements (using regex):

- Find: `ck[ai]$`, Replace with: `cki`
- Find: `sk[ai]$`, Replace with: `ski`
- Find: `dzk[ai]$`, Replace with: `dzki`

Report generator would then apply those replacements for each surname as they are counted and instead count based on the replacement output.

---

NB: I know the frequency of names report is on bottom of the importance list of GEDKeeper modules, so I don't really expect it to be implemented, but I figured I might as well open this issue anyway and just suggest it

**Comment by cbettinger** [comment]
Be aware, that the list of replacements you suggested, is not complete. For example the wife of "Konieczny" is "Konieczna".

**Comment by burtek** [comment]
I'm aware of that. That's why I suggested this to be configurable in the
app settings

czw., 2 maj 2024, 12:08 użytkownik Christian Bettinger <
***@***.***> napisał:

**Comment by Serg-Norseman** [comment]
Such functionality exists for the Russian language. But it is implemented as part of the culture class code (the NormalizeSurname function). Nothing prevents us from creating an analogue for the Polish language.

https://github.com/Serg-Norseman/GEDKeeper/blob/master/projects/GKCore/GKCore/Cultures/PolishCulture.cs
https://github.com/Serg-Norseman/GEDKeeper/blob/master/projects/GKCore/GKCore/Cultures/RussianCulture.cs

**Comment by burtek** [comment]
That works, too. I can and come up with a PR based on the russian code.

Does that mean though, the behaviour will depend on the language set by the user?

**Comment by Serg-Norseman** [comment]
Yes

**Comment by burtek** [comment]
So that means it won't work for me if I'm using English language... :/

**Comment by Serg-Norseman** [comment]
Cultures are tied not to the interface language, but to the language of the database (File\Properties) or to the language of each individual person name.

**Comment by burtek** [comment]
Oh, gotcha. Makes more sense. Thanks.

**Comment by Serg-Norseman** [comment]
You improved localization into Polish and did this PR. According to my principles, I must mention you in the history of the project. Tell me, please, in what form do you prefer: nick (burtek), first name (Bartosz) or will you provide the full name?

**Comment by burtek** [comment]
either works :) I usually default to my username when coding, so let's go with that

**Comment by Serg-Norseman** [comment]
Ok :)
