### ISSUE TITLE
Charts "Show places > Only locality" option

### ISSUE THREAD

**Issue by burtek** [Serg-Norseman/GEDKeeper#558]
Given Location of "City,Region,Country", pre-3.6.0 "Only locality" option for charts would show "City" in the chart. As of 3.6.0 it shows "Country". Is this expected?

**Comment by Serg-Norseman** [comment]
Try the "Specials \ Reverse order of places" option

**Comment by burtek** [comment]
That worked, thanks. Still, something must have changed :thinking: 

Good enough for me, can close if you are not planning on changing anything here

**Comment by Serg-Norseman** [comment]
There, the previously made code was simply systematized for compatibility with the new implementation, which provides partial support for GEDCOM 5.5 EL.

Therefore, a couple of old functions began to work in reverse.
