### ISSUE TITLE
Filtering is now case-sensitive

### ISSUE THREAD

**Issue by burtek** [Serg-Norseman/GEDKeeper#562]
As of 3.6.0:

![image](https://github.com/Serg-Norseman/GEDKeeper/assets/2940958/6783c6f5-3fee-4611-a415-9a776be176ad)
![image](https://github.com/Serg-Norseman/GEDKeeper/assets/2940958/dde618a5-7d16-4f45-b094-e83069ef0130)

Used to be case insensitive (both `Wilk` and `wilk` would yield same two results in my case pre-3.6.0)

**Comment by Serg-Norseman** [comment]
Yes, that's how it was intended here.
A new experimental algorithm has been introduced, which is 12 times faster if a case-sensitive path is used, and 4-5 times faster if a case-insensitive path is used. Perhaps later I will make an option that allows to choose between three options: the old one and two new ones. While I'm thinking

**Comment by burtek** [comment]
case-insensitive was better for me, was able to quickly find a place with one hand (no need to press Shift), so I'd be happy to get an option for that :)
