### ISSUE TITLE
Untranslated entries in "User reference" dialog {bug}

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#57]
When user adds new or edits an existing reference, he/she may see untranslated text in "User reference" dialog if one views the reference’s popup list.

The screenshot below shows what I mean (the screenshot was made from GK run with ENU localization):

![gk-bug](https://cloud.githubusercontent.com/assets/16339987/18831765/09249d4a-8401-11e6-9c04-9b86b427eb4f.png)

**Comment by Serg-Norseman** [comment]
Improved structure of localization files and their reading, now it is possible to segment and reserve areas. Predefined custom links are transfered to localization files.
