### ISSUE TITLE
Interfaces that do not allow multi-lingual translating

### ISSUE THREAD

**Issue by Huaweidev** [Serg-Norseman/GEDKeeper#571]
Interfaces that do not allow multilingual translation, hope can provide translation file:
1. the entire report menu
2. some of the following plugins
3. Full tree - boarder
```
Communicator
Stream input..
DNA Analysis
HistoryData
Conway's Game of Life
Names book
Import pedigrees
```

[Image A: Conway's Game of Life]
![06-15_14-02-32](https://github.com/Serg-Norseman/GEDKeeper/assets/10258421/2dad7b58-7032-40ce-82d1-cb0768870404)

[Image B: report menu]
![06-15_13-53-17](https://github.com/Serg-Norseman/GEDKeeper/assets/10258421/952612fe-732a-41f0-b6d1-75464aee13ac)

[Image C: plugins]
![06-15_14-00-27](https://github.com/Serg-Norseman/GEDKeeper/assets/10258421/9435c332-6c0a-46ec-8300-4efa92812cd6)

[Image D: Full tree - boarder]
![06-15_15-21-18](https://github.com/Serg-Norseman/GEDKeeper/assets/10258421/34bec3e3-fafa-4afe-95a7-287d951f6639)

**Comment by Serg-Norseman** [comment]
1. Menu "Plugins"
 - Communicator, DNA Analysis - experimental unfinished subproject; unlikely to be completed, decommissioning required;
 - Stream input, Names book, Import pedigrees - extremely specific to Russia, dubious prospects for universality, should be disabled for other localizations;
 - HistoryData - unfinished; I need to find a resource and decide what to do next;
 - Conway's Game of Life - I'll finalize it

2. Borders - at the request of another user, it was made localizable two days ago, this evening I will update the files on Crowdin;
