### ISSUE TITLE
Add support for full names without line breaks

### ISSUE THREAD

**Issue by Huaweidev** [Serg-Norseman/GEDKeeper#572]
Add support for full names without line breaks, some countries have very short characters for names. Line breaks are not so easy to read.
* Name example: x xx.

It is short and does not need line breaks.

**Comment by Serg-Norseman** [comment]
Need some clarification - "line breaks in full names" - where is this?

**Comment by Huaweidev** [comment]
> Need some clarification - "line breaks in full names" - where is this?

In the full tree diagram. Here's an English name, in fact I need the format to have no line breaks in the other language.
![06-15_20-25-24](https://github.com/Serg-Norseman/GEDKeeper/assets/10258421/57d95df7-df46-460f-ade5-a6fd6d6385ae)
