### ISSUE TITLE
Interface improvement: No. column is too narrow for other language and can't remember width

### ISSUE THREAD

**Issue by Huaweidev** [Serg-Norseman/GEDKeeper#573]
Interface improvement: 
1. The No. column is too narrow for other languages. It doesn't show all my characters. I'd like to request that the default width in each window, e.g.: individual, family, etc., be changed to double the current width.

 2. And I can't remember the width, I drag it to the appropriate width and close the window, it's narrow again when I open the window.

![06-15_15-02-12](https://github.com/Serg-Norseman/GEDKeeper/assets/10258421/37f66f40-d1c1-4611-aff2-343ab1f26bbc)

**Comment by Serg-Norseman** [comment]
Yes, remembering the width was done only for person columns; for other lists it was decided not to be necessary. You are the first one to ask :)
