### ISSUE TITLE
Change removing confirmation text {proposal}

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#58]
"Remove the user reference" confirmation should be "Do you want to remove the user reference?" or "Are you sure you want to remove the user reference?". Or, even better: "Do you want to remove reference '*REFERENCE NAME*'?" / "Are you sure you want to remove reference '*REFERENCE NAME*'?"

![gk-bug-2](https://cloud.githubusercontent.com/assets/16339987/18831834/6985c1d2-8401-11e6-9b72-73adeb805223.png)

**Comment by ruslangaripov** [comment]
@Serg-Norseman Since you have added me to contributor list I tried to fix this ticket by myself :blush:

**Comment by ruslangaripov** [comment]
Neither 9b64605 nor 07efd69 contain auto-close message. They just refer this ticket.

Therefore, as owner of the repository you have to close this ticket directly. It was successfully resolved by now. :smiley:

**Comment by Serg-Norseman** [comment]
Fixes 9b64605ecc58af6347074e1da5e5778b72bf1880 and 07efd697207ac675be25f3ee777d177053840b3e.
