### ISSUE TITLE
"Disconnect" buttons are always enabled {unwanted behavior}

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#59]
Person editor window has "disconnect" buttons that are always enabled. Even when the "*Parent*" field is empty. While the neighboring button "Go to" to the right of "Disconnect" button is enabled only if a parent exists.

And about “Detach link to father/mother?” confirmation text -- see ticket #58 

![gk-bug-3](https://cloud.githubusercontent.com/assets/16339987/18831915/e6626fb6-8401-11e6-9c85-41f6f6ff3628.png)

**Comment by Serg-Norseman** [comment]
Fix 4b1e5b2e542825d4c6d8275e54b3aeea0cf305e6
