### ISSUE TITLE
Add option to simplify display of maiden surnames in extended mode (if there is only one surname)

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#598]

**Comment by peepay** [comment]
Thanks for creating this issue on my behalf. The idea was to not include the parentheses in case only one surname exists, i.e.:

For married women:
Firstname Married (Maiden)
And for unmarried women:
Firstname Maiden

This is the expected way of writing the names in my region.
Thanks in advance!
