### ISSUE TITLE
Parent removing persists after user canceled editing {bug}

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#60]
Steps to reproduce:
1. Open a person in editor window, for example, 'BLYTHE William Jefferson',
2. Click "Disconnect father" button,
3. Answer "Yes" to confirmation,
4. **Click "Cancel" button**,
5. Edit the same person again ('BLYTHE William Jefferson'). Now the person has no father, despite the fact that user has pressed "Cancel" button previously.

![gk-bug-4](https://cloud.githubusercontent.com/assets/16339987/18832000/5d9350d2-8402-11e6-9373-b90611f1c836.png)

**Comment by Serg-Norseman** [comment]
This is a great find! This problem revealed at least three other flaws.

**Comment by ruslangaripov** [comment]
A small ticket that will lead to big changes :smiling_imp:

**Comment by Serg-Norseman** [comment]
Oh yeah! 👍 😄

**Comment by Serg-Norseman** [comment]
Closed in error instead of 59.

**Comment by Serg-Norseman** [comment]
In the evening I sending the current implementation for this issue...

**Comment by ruslangaripov** [comment]
:+1: I'm looking forward to your patch. Even partial one.

**Comment by Serg-Norseman** [comment]
Now, it is only the parents of the individual and spouses in families
