### ISSUE TITLE
Bugs in CommonFilterDlg

### ISSUE THREAD

**Issue by cbettinger** [Serg-Norseman/GEDKeeper#606]
Today is noticed two bugs in the filter dialog:

![CommonFilterDlg](https://github.com/user-attachments/assets/0771bc0d-1e83-4b22-9f6d-4fa5d621937f)

1. The dialog title is always "CommonFilterDlg", no matter if I set the language to English or German.
2. I tried to show only notes that contain a question mark using the filter dialog, but that has no effect. All notes are still shown.

**Comment by Serg-Norseman** [comment]
There may be problems with the question mark - it is generally interpretable in filters. But in the condition "contains" it should not be. I think it can be fixed.
