### ISSUE TITLE
Unable to select an unsaved entry when editing another one

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#70]
I can’t use an unsaved entry as a reference in another entry (existing or not).

Here are steps to reproduce:

1. Open an existing database or create a new one.
![gk-bug-01-01](https://cloud.githubusercontent.com/assets/16339987/18951499/f50a2c3e-865e-11e6-8cac-fb0b2619b918.png)
2. Add a new person to the database. You may optionally save the database now. If you have opened an existing database, you may skip this step.
![gk-bug-01-02](https://cloud.githubusercontent.com/assets/16339987/18951513/06840d2c-865f-11e6-9b50-6aa37409069d.png)
3. Add another person to the database, but **do not save** your changes now.
![gk-bug-01-02-1](https://cloud.githubusercontent.com/assets/16339987/18951516/0d25db42-865f-11e6-86d2-54fecfdbeb00.png)
4. Edit the first person, you create at the step 2 (or just select a person without father or/and mother if you have skipped that step).
5. Click "Add father" or "Add mother" button to open selector window.
![gk-bug-01-03](https://cloud.githubusercontent.com/assets/16339987/18951531/1f8cf5d6-865f-11e6-9dc2-5f2b6b6e1d30.png)
![gk-bug-01-04](https://cloud.githubusercontent.com/assets/16339987/18951532/1f979c7a-865f-11e6-9829-fa3e6d908b30.png)

As you can see one can’t select the new person one has created at the step 3 (i.e. there is no "4 5 6" person available to select).

**Comment by Serg-Norseman** [comment]
It's not a bug, but a feature :) you have a second person, which without specifying gender, therefore, cannot be selected as a father or mother or even spouse

**Comment by ruslangaripov** [comment]
Okay :ok_hand:

Thus close by design.
