### ISSUE TITLE
Russian help content says: "GEDKeeper ain't a cross-platform one"

### ISSUE THREAD

**Issue by ruslangaripov** [Serg-Norseman/GEDKeeper#9]
There is a disadvantage item on "Advantages and features" page ('gkhFeatures.html' file) claiming that "The program supports only Windows, it ain't a cross-platform project and it can't be built with 'Mono' under Linux". **It lies!** :laughing: And I believe this paragraph must be removed from Russian help content, while I won't add this item in English help content at all. Am I right? :smiling_imp:

**Comment by Serg-Norseman** [comment]
Yes, that's right. It needs to be removed :smile:

**Comment by ruslangaripov** [comment]
And may be we should add an advantage item? Something like:

  * GEDKeeper supports both Linux and Windows. It is a cross-platform project; one can build release on Linux or Windows operating systems.

**Comment by Serg-Norseman** [comment]
Early, but possible

**Comment by ruslangaripov** [comment]
Anyway, GEDKeeper will be such a project. Even now it's on its way to this. So, I believe we can say this.

**Comment by ruslangaripov** [comment]
OK, I

- [x] didn't add topic item to English help content,
- [x] add an advantage item saying that GEDKeeper **is** cross-platform :smiling_imp: Well, sooner or later it will!
- [x] did **not** modify Russian help content.
