### ISSUE TITLE
Relative and absolute paths to the media files aren't shared between Windows and Linux

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#94]

**Comment by ruslangaripov** [comment]
Okay, a way to fix the issue with relative paths is obvious enough -- one can replace backslashes with forward ones on the fly. Of vice versa, if one prefers Microsoft Windows style.

But absolute names of directories -- that's a real pain in the neck. We can leave the issue as is and say: "Oh, dear (advanced) user! Once you had got two OSes, that became your problem. Find a solution by yourself. Bye." But what if we...

1. ...will store both names? I mean that a database will store directory name in Linux style and in Microsoft Windows style. This forces synchronization problem, of course (user have to maintain the mapping between names in actual state, or he/she will get two different media sets for two OSes). Also, this may lead to incompatibility with GEDCOM standard.

2. ...will give an ability to user to support mapping "Linux directory name - MSFT Windows directory name" using some local (per-computer) settings? For example, before GEDKeeper opens a media, it reads a mapping file with the following content:
`/dev/sda3/Users/mitchwilkinson/Pictures/GK:C:\Users\mitchwilkinson\Pictures\GK`
Thus, the file contains mappings between Linux paths and Microsoft Windows ones. Having this information GEDKeeper tries to open a media using **platform-specific** path. In this case, a database must store directory names in one selected format (Linux one, for example) and GEDKeeper transforms a name on the fly using local user mapping.

See also: #90

**Comment by Serg-Norseman** [comment]
It's an interesting thoughts! It should consider...
