### ISSUE TITLE
Control of number of visible generations in the tree chart

### ISSUE THREAD

**Issue by Serg-Norseman** [Serg-Norseman/GEDKeeper#98]
Develop the popup control of number of visible generations in the tree chart (TreeChartBox).

**Comment by Serg-Norseman** [comment]
Not a very good result, but it'll do for now.

**Comment by ruslangaripov** [comment]
There's one result that I've got! 😆 I have to merge your changes with my now! Since we have changed the same files. Conflicts happen 😆  A new PR is around the corner...

**Comment by Serg-Norseman** [comment]
:(
